MAUI-5121 : Prepare Popup positioning UG for .NET MAUI popup
syncfusion-content/maui-docs pull request #1003
Opened 2023-03-17 07:57 UTC by JayashreeRavishankar

Prepare Popup positioning UG for .NET MAUI popup

2023-03-17 07:58 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-5121](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3000/console)**

2023-03-17 07:59 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-5121](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3000/)<br/>**

2023-03-17 08:07 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-5121](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3001/console)**

2023-03-17 10:10 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-5121](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3003/console)**

2023-03-17 10:18 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-5121](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3003/)<br/>**

2023-03-17 10:36 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3004/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2023-03-17 10:37 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-5121](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3005/console)**

2023-03-17 10:42 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-5121](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3005/)<br/>**

2023-03-17 11:10 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-5121](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3009/console)**

2023-03-17 11:11 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-5121](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3009/)<br/>**

2023-03-20 05:07 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-5121](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3034/console)**

2023-03-20 05:07 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-5121](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3034/)<br/>**

2023-03-20 05:12 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-5121](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3035/console)**

2023-03-20 05:13 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-5121](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3035/)<br/>**

2023-03-20 06:28 UTC, PiruthivirajM commented on MAUI/Popup/popup-positioning.md
> +	sfPopup.IsOpen = true;
highlight the line

2023-03-20 06:30 UTC, PiruthivirajM commented on MAUI/Popup/popup-positioning.md
> +	sfPopup.Show();
Highlight code

2023-03-20 06:31 UTC, PiruthivirajM commented on MAUI/Popup/popup-positioning.md
> +	 sfPopup.Show(50, 200);
highlight the code

2023-03-20 06:33 UTC, PiruthivirajM commented on MAUI/Popup/popup-positioning.md
> +	sfPopup.ShowRelativeToView(clickToShowPopup, PopupRelativePosition.AlignBottom, 0, 0);
check the comment line alignment.
Highlight the code

2023-03-20 06:42 UTC, PiruthivirajM commented on MAUI/Popup/popup-positioning.md
> +![Popup with center positioning](Images/popup-positioning/maui-popup-with-center-positioning.png)
![Displaying a .NET MAUI Popup at the center of the screen.]
Include .NET MAUI in all image alt text

2023-03-20 06:43 UTC, PiruthivirajM commented on MAUI/Popup/popup-positioning.md
> +      <sfPopup:SfPopup x:Name="sfPopup" IsOpen="{Binding DisplayPopup}"
<sfPopup:SfPopup x:Name="sfPopup" 
                               IsOpen="{Binding DisplayPopup}".
                               
Modify like above and hightlight "IsOpen" code

2023-03-20 06:44 UTC, PiruthivirajM commented on MAUI/Popup/popup-positioning.md
> +  (this.BindingContext as ViewModel).DisplayPopup = true;
highlight the code

2023-03-20 06:46 UTC, PiruthivirajM commented on MAUI/Popup/popup-positioning.md
> +You can pass both negative and positive values as parameters to the SfPopup.ShowRelativeToView(View, RelativePosition, x-position, y-position). The popup will be positioned by considering the relativ
highlight the APIs in content

2023-03-20 06:50 UTC, PiruthivirajM reviewed
Address review comments

2023-03-20 06:50 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-5121](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3039/console)**

2023-03-20 06:51 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-5121](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3039/)<br/>**

2023-03-20 07:33 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-5121](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3043/console)**

2023-03-20 07:34 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-5121](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3043/)<br/>**

2023-03-21 07:30 UTC, M-A32 requested changes

2023-03-21 07:30 UTC, M-A32 commented on MAUI/Popup/popup-positioning.md
> +You can pass both negative and positive values as parameters to the `SfPopup.ShowRelativeToView(View, RelativePosition, x-position, y-position)`. The popup will be positioned by considering the relat
You can pass both negative and positive values as parameters to the `SfPopup.ShowRelativeToView(View, RelativePosition, x and y-position).` The popup will be positioned by considering the relative position as (0, 0) the center point. For example, if you have set the `RelativePosition` as `PopupRelativePosition.AlignBottomRight` and `RelativeView` as a button, bottom right corner of the button will be considered as the 0, 0 point and a negative x-position value will place the popup to the left of that point and a positive x-position value will place the popup to the right of that point. The same applies for y-position.

2023-03-21 07:30 UTC, M-A32 commented on MAUI/Popup/popup-positioning.md
> +  // Shows SfPopup at the bottom of the label and with absolute relative position.
// Show the SfPopup at the bottom of the label and with absolute relative position.

2023-03-21 08:06 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-5121](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3072/)<br/>**

2023-03-21 10:43 UTC, PiruthivirajM approved these changes
Approved

2023-03-21 10:44 UTC, merged