MAUI-5238 : Prepare UG for Popup Events and Commands in .NET MAUI popup
syncfusion-content/maui-docs pull request #1010
Opened 2023-03-20 05:54 UTC by RiyashameedM

Prepared UG for Popup Events and Commands in .NET MAUI popup

2023-03-20 05:55 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-5238](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3036/console)**

2023-03-20 05:56 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-5238](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3036/)<br/>**

2023-03-20 05:59 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-5238](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3037/console)**

2023-03-20 06:00 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-5238](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3037/)<br/>**

2023-03-20 06:53 UTC, PiruthivirajM commented on MAUI/Popup/Popup-Events.md
> +    e.Cancel = true;
Highlight this line too

2023-03-20 06:57 UTC, PiruthivirajM commented on maui-toc.html
> +            <li><a href="/maui/Popup/Popup-Events">Popup Events And Commands</a></li>
Event and Commands

2023-03-20 06:57 UTC, PiruthivirajM reviewed
Address review comments

2023-03-20 09:07 UTC, RiyashameedM commented on maui-toc.html
> +            <li><a href="/maui/Popup/Popup-Events">Popup Events And Commands</a></li>
modified

2023-03-20 09:07 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-5238](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3045/console)**

2023-03-20 09:08 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-5238](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3045/)<br/>**

2023-03-20 13:20 UTC, M-A32 requested changes

2023-03-20 13:20 UTC, M-A32 commented on MAUI/Popup/Popup-Events.md
> +* Now create a property of your custom command type in the view model class and initialize it.
* Now, create a property of your custom command type in the view model class and initialize it.

2023-03-20 13:20 UTC, M-A32 commented on MAUI/Popup/Popup-Events.md
> +* Derive a class from `ICommand`, and implement the `ICommand` interface.
* Derive a class from the `ICommand`, and implement its interface.

2023-03-20 13:53 UTC, RiyashameedM commented on MAUI/Popup/Popup-Events.md
> +* `Cancel`: Popup opening is based on this value.
resolved

2023-03-20 13:53 UTC, RiyashameedM commented on MAUI/Popup/Popup-Events.md
> +* Derive a class from `ICommand`, and implement the `ICommand` interface.
modified

2023-03-20 13:53 UTC, RiyashameedM commented on MAUI/Popup/Popup-Events.md
> +* To prevent popup from closing, return false in the `CanExecute()` override method and the `Execute()` override method will not be fired.
modified

2023-03-20 13:53 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-5238](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3059/console)**

2023-03-20 13:54 UTC, RiyashameedM commented on MAUI/Popup/Popup-Events.md
> +* To prevent popup from closing, return false in the `CanExecute()` override method and the `Execute()` override method will not be fired.
modified

2023-03-20 13:54 UTC, RiyashameedM commented on MAUI/Popup/Popup-Events.md
> +The `SfPopup.Closing` event will be fired whenever closing the Popup in the application. It can cancel popup closing with `CancelEventArgs` that contains the following property:
modified

2023-03-20 13:54 UTC, RiyashameedM commented on MAUI/Popup/Popup-Events.md
> +* `Cancel`: Popup opening is based on this value.
resolved

2023-03-20 13:54 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-5238](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3059/)<br/>**

2023-03-20 13:55 UTC, RiyashameedM commented on MAUI/Popup/Popup-Events.md
> +description: Learn here all about Popup Events And Commands support in Syncfusion .NET MAUI Popup (SfPopup) control and more.
modified

2023-03-20 13:57 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-5238](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3060/)<br/>**

2023-03-20 13:58 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-5238](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3061/console)**

2023-03-20 13:59 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-5238](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3061/)<br/>**

2023-03-21 08:21 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-5238](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3073/console)**

2023-03-21 11:40 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-5238](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3082/)<br/>**

2023-03-21 11:43 UTC, RiyashameedM commented
rebuild

2023-03-21 11:57 UTC, closed without merging