MAUI-5269 : Prepare UG for Working with MVVM and Modal window in .NET MAUI popup
syncfusion-content/maui-docs pull request #1046
Opened 2023-03-24 07:27 UTC by JayashreeRavishankar

Prepare UG for Working with MVVM and Modal window in .NET MAUI popup

2023-03-24 07:28 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [MAUI_5269_hotfix](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3151/console)**

2023-03-24 07:33 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI_5269_hotfix](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3151/console)**

2023-03-24 07:34 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI_5269_hotfix](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3151/)<br/>**

2023-03-24 12:14 UTC, jayaleshwari commented on MAUI/Popup/modal-window.md
> +You can use popup as modal window by using the built-in Close icon and the `SfPopup.StaysOpen` property prevents interaction with your application until you close the window.
Need cpas here for Close

2023-03-24 12:17 UTC, jayaleshwari commented on MAUI/Popup/modal-window.md
> +![.NET MAUI Popup as Modal Window](Images/modal-window/maui-popup-modal-window.png)
change alt text to .NET MAUI Popup as modal window

2023-03-24 12:24 UTC, jayaleshwari commented on MAUI/Popup/working-with-mvvm.md
> +`SfPopup` can be used in MVVM architecture applications easily. In the below example `SfPopup.IsOpen` property is bound to a property in the ViewModel based on which the popup is opened or closed. Re
highlight ViewModel

2023-03-24 12:33 UTC, jayaleshwari commented on MAUI/Popup/working-with-mvvm.md
> +In the below code snippet, note that the Binding context is set for the page and the property (DisplayPopup) of the ViewModel is bound to the `SfPopup.IsOpen`.
use BindingContext as tech word. or use binding context

2023-03-24 12:34 UTC, jayaleshwari commented on MAUI/Popup/working-with-mvvm.md
> +                             IsOpen="{Binding DisplayPopup}">
use property name as like bool property

2023-03-24 12:34 UTC, jayaleshwari commented on MAUI/Popup/working-with-mvvm.md
> +    private void OpenPopup()
OnOpenPopup

2023-03-24 12:35 UTC, jayaleshwari commented on MAUI/Popup/working-with-mvvm.md
> +    public bool OpenPopup
use bool convention for property name

2023-03-24 12:35 UTC, jayaleshwari commented on MAUI/Popup/working-with-mvvm.md
> +    private void Login()
OnLogin

2023-03-27 04:50 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI_5269_hotfix](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3167/console)**

2023-03-27 04:51 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI_5269_hotfix](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3167/)<br/>**

2023-03-27 04:56 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI_5269_hotfix](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3168/console)**

2023-03-27 04:57 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI_5269_hotfix](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3168/)<br/>**

2023-03-27 05:04 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI_5269_hotfix](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3169/console)**

2023-03-27 05:05 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI_5269_hotfix](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3169/)<br/>**

2023-03-27 05:06 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI_5269_hotfix](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3170/console)**

2023-03-27 05:07 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI_5269_hotfix](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3170/)<br/>**

2023-03-27 06:21 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI_5269_hotfix](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3175/)<br/>**

2023-03-27 06:56 UTC, florenceliliana requested changes
The PR review is completed.

2023-03-27 06:56 UTC, florenceliliana commented on MAUI/Popup/modal-window.md
> +description: Learn here all about Modal Window support in Syncfusion .NET MAUI Popup (SfPopup) control, its elements and more.
description: Learn here all about Modal Window support in the Syncfusion .NET MAUI Popup (SfPopup) control, its elements, and more.

2023-03-27 06:56 UTC, florenceliliana commented on MAUI/Popup/modal-window.md
> +You can use popup as modal window by using the built-in close icon and the [SfPopup.StaysOpen](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.Popup.SfPopup.html#Syncfusion_Maui_Popup_SfPopup_Sta
You can use the popup as a modal window using the built-in close icon and the [SfPopup.StaysOpen](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.Popup.SfPopup.html#Syncfusion_Maui_Popup_SfPopup_StaysOpen) property prevents interaction with your application until you close the window.

2023-03-27 06:56 UTC, florenceliliana commented on MAUI/Popup/modal-window.md
> +Refer to the following code example in which the popup will close only if you click on close icon.
Refer to the following code example: the popup will only close if you click on the close icon.

2023-03-27 06:56 UTC, florenceliliana commented on MAUI/Popup/modal-window.md
> +                    <Label Text="A modal window disables the parent window while the user interacts with the child (modal) window before they return to the parent application."
<Label Text= "A modal window disables the parent window while the user interacts with the child (modal) window before they return to the parent application."

2023-03-27 06:56 UTC, florenceliliana commented on MAUI/Popup/working-with-mvvm.md
> +description: Learn here all about MVVM support in Syncfusion .NET MAUI Popup (SfPopup) control, its elements and more.
description: Learn here all about MVVM support in the Syncfusion .NET MAUI Popup (SfPopup) control, its elements, and more.

2023-03-27 06:56 UTC, florenceliliana commented on MAUI/Popup/working-with-mvvm.md
> +`SfPopup` can be used in MVVM architecture applications easily. In the below example [SfPopup.IsOpen](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.Popup.SfPopup.html#Syncfusion_Maui_Popup_SfPo
`SfPopup` can be used in the MVVM architecture applications easily. In the below example, the [SfPopup.IsOpen](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.Popup.SfPopup.html#Syncfusion_Maui_Popup_SfPopup_IsOpen) property is bound to a property in the `ViewModel` based on which the popup is opened or closed. Refer to the following code example to display the popup in MVVM.

2023-03-27 06:56 UTC, florenceliliana commented on MAUI/Popup/working-with-mvvm.md
> +In the below code snippet, note that the BindingContext is set for the page and the property (IsOpen) of the ViewModel is bound to the [SfPopup.IsOpen](https://help.syncfusion.com/cr/maui/Syncfusion.
In the following code sample, note that the BindingContext is set for the page, and the property (IsOpen) of the ViewModel is bound to the [SfPopup.IsOpen](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.Popup.SfPopup.html#Syncfusion_Maui_Popup_SfPopup_IsOpen).

2023-03-27 06:56 UTC, florenceliliana commented on MAUI/Popup/working-with-mvvm.md
> +To use `SfPopup` as a page, create a new XAML file with `SfPopup` in it. You can use this XAML file instance (SfPopup view), across any file in your project wherever you may want to display a popup,
To use the `SfPopup` as a page, create a new XAML file with `SfPopup`. You can use this XAML file instance (SfPopup view) across any file in your project wherever you may want to display a popup, thus allowing you to re-use the same instance of the popup where you can modify or change the required properties alone based on the current context to be displayed.

2023-03-27 06:56 UTC, florenceliliana commented on MAUI/Popup/working-with-mvvm.md
> +The below code snippet shows how to create a popup in XAML file. We have created a simple popup to show error message popup to user on a unsuccessful login.
The following code sample shows how to create a popup in a XAML file. We have created a simple popup to display an error message popup to users on an unsuccessful login.

2023-03-27 06:56 UTC, florenceliliana commented on MAUI/Popup/working-with-mvvm.md
> +The below code snippet shows how to consume the previously created SfPopup page from inside a different content page.
The following code sample shows how to consume the previously created SfPopup page from inside a different content page.

2023-03-27 06:56 UTC, florenceliliana commented on MAUI/Popup/working-with-mvvm.md
> +Refer to the following code example to retrieve text value from entry control in MAUI popup content template.
Refer to the following code example to retrieve text value from entry control in the MAUI popup content template.

2023-03-27 08:26 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI_5269_hotfix](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3188/console)**

2023-03-27 08:28 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI_5269_hotfix](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3188/)<br/>**

2023-03-28 11:37 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI_5269_hotfix](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3225/console)**

2023-03-28 11:38 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI_5269_hotfix](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3226/)<br/>**

2023-03-28 11:48 UTC, jayaleshwari approved these changes
This is fine

2023-03-28 11:49 UTC, merged