Prepare Style UG for .NET MAUI Popup
syncfusion-content/maui-docs pull request #1048
Opened 2023-03-24 11:12 UTC by RiyashameedM

Prepared Style UG for .NET MAUI Popup

2023-03-24 11:13 UTC, SyncfusionBuild commented
The merge request title does not contain the JIRA task ID or the given JIRA task ID is not a valid ID. Please update the corresponding JIRA task ID in your merge request title. After updating, type **rebuild** in the comment section to rerun the CI. The merge request title format should be **Task ID - Merge request title** (OR) **Type(Task ID): Merge request title**. Example: CI-1012 - Title, bug(JS-1234): Title.

2023-03-24 11:13 UTC, RiyashameedM commented
rebuild

2023-03-24 11:14 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-5256](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3157/console)**

2023-03-24 11:15 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-5256](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3157/)<br/>**

2023-03-24 13:38 UTC, jayaleshwari requested changes
Please address review comments

2023-03-24 13:38 UTC, jayaleshwari commented on MAUI/Popup/styles.md
> +![Displaying a .NET MAUI Popup with blur](/Images/styles/maui-popup-with-blurred-background.png)
Displaying a .NET MAUI Popup with blur overlay

2023-03-27 06:10 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [MAUI-5256](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3171/console)**

2023-03-27 06:13 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-5256](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3171/console)**

2023-03-27 06:15 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-5256](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3171/)<br/>**

2023-03-27 06:26 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-5256](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3176/console)**

2023-03-27 06:27 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-5256](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3176/)<br/>**

2023-03-27 06:34 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-5256](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3177/console)**

2023-03-27 06:35 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-5256](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3177/)<br/>**

2023-03-27 06:38 UTC, PiruthivirajM approved these changes
approved

2023-03-27 07:55 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-5256](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3186/console)**

2023-03-27 07:57 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-5256](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3186/)<br/>**

2023-03-27 09:53 UTC, RiyashameedM commented on MAUI/Popup/styles.md
> +![Displaying a .NET MAUI Popup with blur](/Images/styles/maui-popup-with-blurred-background.png)
modified

2023-03-27 09:53 UTC, RiyashameedM commented on MAUI/Popup/styles.md
> +The SfPopup allows you adjust the opacity of the overlay color by setting the color value to "#30FF0000". The first two digits represent opacity in hexadecimal format, while the remaining six digits
modified

2023-03-28 11:31 UTC, jayaleshwari approved these changes
This is fine

2023-03-28 11:33 UTC, merged