827157-Prepare UG documentation for the range area support in .NET  MAUI
syncfusion-content/maui-docs pull request #1128
Opened 2023-05-12 06:48 UTC by DhanarajRajendran

### Feature description ###

Added the User Guide for Range Area series Chart

### Output ###

<img width="743" alt="Screenshot 2023-05-02 105019 (3)" src="https://github.com/syncfusion-content/maui-docs/assets/126753532/6fca9ef6-a05c-44c3-a83a-b74c24048253">

## ##

<img width="760" alt="Screenshot 2023-04-26 170041 (2)" src="https://github.com/syncfusion-content/maui-docs/assets/126753532/59498a98-45cc-4c30-a9b0-96d6765f47c7">

2023-05-12 06:48 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [827157-Prepare-UG-documentation-for-the-range-area-support-in-.NET-MAUI](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3324/console)**

2023-05-19 09:15 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [827157-Prepare-UG-documentation-for-the-range-area-support-in-.NET-MAUI](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3337/console)**

2023-05-19 09:16 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [827157-Prepare-UG-documentation-for-the-range-area-support-in-.NET-MAUI](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3337/)<br/>**

2023-05-29 11:44 UTC, florenceliliana requested changes

2023-05-29 11:44 UTC, florenceliliana commented on MAUI/Cartesian-Charts/RangeArea.md
> +title: Range Area Chart in .NET MAUI Chart control | Syncfusion
title: Range Area Chart in .NET MAUI Chart Control | Syncfusion

2023-05-29 11:44 UTC, florenceliliana commented on MAUI/Cartesian-Charts/RangeArea.md
> +To render a range area chart, create an instance of [RangeAreaSeries](), and add it to the [Series](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.Charts.SfCartesianChart.html#Syncfusion_Maui_Ch
To render a range area chart, create an instance of the [RangeAreaSeries](), and add it to the [Series](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.Charts.SfCartesianChart.html#Syncfusion_Maui_Charts_SfCartesianChart_Series) collection property of [SfCartesianChart](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.Charts.SfCartesianChart.html?tabs=tabid-1).

2023-05-29 11:44 UTC, florenceliliana commented on MAUI/Cartesian-Charts/RangeArea.md
> +N> The Cartesian chart has [Series](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.Charts.SfCartesianChart.html#Syncfusion_Maui_Charts_SfCartesianChart_Series) as its default content.
N> The Cartesian chart has a [Series](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.Charts.SfCartesianChart.html#Syncfusion_Maui_Charts_SfCartesianChart_Series) as its default content.

2023-05-29 11:44 UTC, florenceliliana commented on MAUI/Cartesian-Charts/RangeArea.md
> +A marker, also known as a symbol, is used to determine or highlight the position of the data point. To enable markers in the series, set the [ShowMarkers](https://help.syncfusion.com/cr/maui/Syncfusi
A marker, also known as a symbol, is used to determine or highlight the position of the data point. To enable markers in the series, set the [ShowMarkers](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.Charts.AreaSeries.html#Syncfusion_Maui_Charts_AreaSeries_ShowMarkers) property to true.

2023-05-29 11:44 UTC, florenceliliana commented on MAUI/Cartesian-Charts/RangeArea.md
> +In order to change the series markers appearance, create an instance of the [MarkerSettings](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.Charts.AreaSeries.html#Syncfusion_Maui_Charts_AreaSeri
In order to change the series marker's appearance, create an instance of the [MarkerSettings](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.Charts.AreaSeries.html#Syncfusion_Maui_Charts_AreaSeries_MarkerSettings) property. The following properties are used to customize the marker's appearance.

2023-05-31 05:31 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [827157-Prepare-UG-documentation-for-the-range-area-support-in-.NET-MAUI](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3360/console)**

2023-05-31 05:32 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [827157-Prepare-UG-documentation-for-the-range-area-support-in-.NET-MAUI](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3360/)<br/>**

2023-06-08 05:29 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [827157-Prepare-UG-documentation-for-the-range-area-support-in-.NET-MAUI](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3399/console)**

2023-06-08 05:30 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [827157-Prepare-UG-documentation-for-the-range-area-support-in-.NET-MAUI](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3399/)<br/>**

2023-06-13 05:26 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [827157-Prepare-UG-documentation-for-the-range-area-support-in-.NET-MAUI](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3457/console)**

2023-06-13 05:46 UTC, Saravanan-Madhesh approved these changes
The changes are fine

2023-06-13 05:48 UTC, merged