MAUI 829675 - UG documentation for Crop and Transform in MAUI Image Editor
syncfusion-content/maui-docs pull request #1195
Opened 2023-06-14 11:43 UTC by Shalini-Ashokan

2023-06-14 11:44 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3490/console)**

2023-06-14 11:46 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3490/)<br/>**

2023-06-15 10:55 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +
Explain these topics

## Free hand crop
## Original Crop
## Square Crop
## Ratio crop

2023-06-15 11:01 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +layout: post
Remove images, will be added properly.
For links use like this, will add links after release  - `Crop`

2023-06-15 11:03 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +
Explain about SaveEdit and Cancel edit to save or cancel the crop action

2023-06-15 11:20 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3525/console)**

2023-06-15 11:20 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3525/)<br/>**

2023-06-15 13:23 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3532/)<br/>**

2023-06-16 05:49 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3549/console)**

2023-06-16 05:50 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3549/)<br/>**

2023-06-16 09:05 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +### Handling the cropping tool
use 2#

2023-06-16 09:05 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +### Original Crop
2#

2023-06-16 09:05 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +### Square Crop
2#

2023-06-16 09:05 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +### Ratio Crop
2#

2023-06-16 09:06 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +### Circle cropping
2#

2023-06-16 09:06 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +// To crop an image as a elliptical dimension.
remove comment

2023-06-16 09:06 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +### Programmatically selecting the cropping ratio
2#

2023-06-16 09:51 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3557/console)**

2023-06-16 09:52 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3557/)<br/>**

2023-06-16 09:53 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3558/console)**

2023-06-16 09:54 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3558/)<br/>**

2023-06-16 10:04 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3561/console)**

2023-06-16 10:05 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3561/)<br/>**

2023-06-16 10:33 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +The square crop option allows you to crop the image into a perfect square shape. This is useful when you want to create square thumbnails or profile pictures.
Remove use - this is useful when you want to create square thumbnails or profile pictures.

2023-06-16 10:34 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +You can also crop an image in a circular or elliptical format, which is useful for profile pictures. Use the `Crop` method with an empty Rect and set the isEllipse parameter to true.
You can crop an image in a circular or elliptical format.

2023-06-16 10:34 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +The following image show cases the circularly cropped image.
remove - The following image show cases the circularly cropped image.

2023-06-16 10:36 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +## Circle cropping
Mention

## Circle Crop
mention that is maintains the circle in 1: 1 ratio


## Ellipse crop
Free style cropping in elliptical shape

2023-06-16 10:37 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +imageEditor.Crop(1,1);
imageEditor.Crop(ImageCropType.Square);

2023-06-16 10:40 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +imageEditor.Crop(16,9);
mention if specified ImageCropType.Ratio is used we consider default ratio 4: 3 and if you want to change the ratio you can use crop method with ratio imageEditor.Crop(16,9);

2023-06-16 10:40 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +imageEditor.Crop(new Rect(20,20,50,50), true);
imageEditor.Crop(new Rect(20,20,50,50), true);

2023-06-16 10:41 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +To manually enter the cropping area without enabling the cropping functionality, use the overloaded `Crop(Rect rect)` method. It can be done by simply define a rectangle and pass it to the `Crop` met
Mention here, if isEllpitical set to true it will consider the ellipse crop

2023-06-16 10:42 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +imageEditor.Crop(new Rect(50,50,150,200));
add ellipse code in another tab

2023-06-16 10:42 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +* To crop an image in a circle or an ellipse with a specific ratio, use `Crop` with a ratio argument and an optional parameter of true, which specifies whether the cropping panel should be added in a
Remove here and add in above topic 

To crop an image in a circle or an ellipse with a specific ratio, use `Crop` with a ratio argument and an optional parameter of true, which specifies whether the cropping panel should be added in an elliptical or rectangle shape. The default value is `false`.

{% capture codesnippet6 %}

{% highlight C# %}

imageEditor.Crop(new Rect(20,20,50,50), true);

2023-06-16 13:21 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3570/console)**

2023-06-16 13:22 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3570/)<br/>**

2023-06-16 13:47 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3571/console)**

2023-06-16 13:55 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3571/)<br/>**

2023-06-19 06:41 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +description: Learn here all about Crop support in Syncfusion .NET MAUI ImageEditor (SfImageEditor) control and more.
Learn here all about crop support in Syncfusion .NET MAUI ImageEditor (SfImageEditor) control.

2023-06-19 06:43 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +platform: MAUI
.Net MAUI

2023-06-19 06:56 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +You can use the cropping tool in the Image Editor to select and crop a specific portion of an image.
Using the Image Editor's cropping tool, you can select and crop a particular section of an image.

2023-06-19 06:58 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +The Image Editor control provides various selection options for cropping images, including custom, square, circle, and customized to various aspects ratios. You can drag and resize the selection regi
The Image Editor control provides a range of selection choices for cropping images, such as custom, square, circle, and different aspect ratios. To crop a specific area of an image, simply drag and resize the selection region.

2023-06-19 06:59 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +Cropping operation can be done in the following two ways:
There are two methods to perform the cropping operation:

* Enable cropping and visually choose the cropping area.
* Input the cropping region manually.

2023-06-19 07:00 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +N> You can also crop the image at a specific position with annotations.
You can also crop the image with annotations.

2023-06-19 07:05 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +This type of crop allows you to freely select and crop a region of the image. You can manually outline the desired area using your cursor or touch input.The selection region can be customized by drag
The selection region can be customized by dragging and resizing.

2023-06-19 07:09 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +You can crop an image in a circular format, specifically for profile pictures, you can use the `Crop` method. This method ensures that the image is cropped into a perfect circle with a 1:1 ratio.
You can crop an image in a circular format using the `ImageCropType.Circle` crop type. This method ensures that the image is cropped into a perfect circle with a 1:1 ratio.

2023-06-19 07:09 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +To crop an image in an elliptical format, such as for profile pictures, you can use the `Crop` method. This allows for free-style cropping in an elliptical shape.
To crop an image in an elliptical format you can use the `ImageCropType.Ellipse` crop type.  This allows for free-style cropping in an elliptical shape.

2023-06-19 07:12 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +imageEditor.Crop(new Rect(50,50,150,200));
imageEditor.Crop(new Rect(50,50,150,200));
imageEditor.SaveEdits();

2023-06-19 07:12 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Crop.md
> +imageEditor.Crop(new Rect(20,20,50,50), true);
imageEditor.Crop(new Rect(20,20,50,50), true);
imageEditor.SaveEdits();

2023-06-19 07:16 UTC, karthikraja-arumugam commented on MAUI/ImageEditor/Transform.md
> +platform: MAUI
platform: .NET MAUI

2023-06-19 08:45 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3593/console)**

2023-06-19 08:46 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3593/)<br/>**

2023-06-19 12:03 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3597/console)**

2023-06-19 12:06 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3597/console)**

2023-06-19 12:08 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3597/)<br/>**

2023-06-19 12:36 UTC, M-A32 requested changes

2023-06-19 12:36 UTC, M-A32 commented on MAUI/ImageEditor/Crop.md
> +title: Crop in .NET MAUI ImageEditor control | Syncfusion
title: Crop in .NET MAUI ImageEditor Control | Syncfusion

2023-06-19 12:36 UTC, M-A32 commented on MAUI/ImageEditor/Crop.md
> +description: Learn here all about crop support in Syncfusion .NET MAUI ImageEditor (SfImageEditor) control.
description: Learn here all about crop support in the Syncfusion .NET MAUI ImageEditor (SfImageEditor) control.

2023-06-19 12:36 UTC, M-A32 commented on MAUI/ImageEditor/Crop.md
> +Using the Image Editor's cropping tool, you can select and crop a particular section of an image.
Using the Image Editor's cropping tool, you can select and crop a section of an image.

2023-06-19 12:36 UTC, M-A32 commented on MAUI/ImageEditor/Crop.md
> +There are two methods to perform the cropping operation:
The following are two methods to perform the cropping operation:

2023-06-19 12:36 UTC, M-A32 commented on MAUI/ImageEditor/Crop.md
> +    * ImageCropType - Specifies the selection type for cropping the image.
* ImageCropType - Specify the selection type for cropping the image.

2023-06-19 12:36 UTC, M-A32 commented on MAUI/ImageEditor/Crop.md
> +After selecting the cropping area, if you decide to cancel the edits and revert back to the original image, you can use the `CancelEdits` method. It discard the changes made during the cropping proce
After selecting the cropping area, if you decide to cancel the edits and revert back to the original image, you can use the `CancelEdits` method. It discards the changes made during the cropping process and restores the image to its initial state.

2023-06-19 12:36 UTC, M-A32 commented on MAUI/ImageEditor/Crop.md
> +The following code sample will add the cropping preview on the image in square shape.
The following code sample will add the cropping preview on the image in a square shape.

2023-06-19 12:57 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3599/console)**

2023-06-19 12:58 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3599/)<br/>**

2023-06-19 13:53 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3604/console)**

2023-06-19 13:54 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3604/)<br/>**

2023-06-19 14:02 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3606/console)**

2023-06-19 14:03 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ImageEditor_Crop_and_Transform](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3606/)<br/>**

2023-06-20 06:15 UTC, karthikraja-arumugam approved these changes
Content is fine

2023-06-20 09:10 UTC, Nijamudeen-Mohamed approved these changes

2023-06-20 09:15 UTC, merged