835280-MapsVideo-Youtube video updated.
syncfusion-content/maui-docs pull request #1340
Opened 2023-07-25 12:48 UTC by IndumathiR-1995

Hi @Sasikumar3595 

Added the youtube video for the MAUI maps control. Please review this and let me know of any concerns.

Regards,
Indumathi R

2023-07-25 12:49 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [835280-MapsVideo](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3900/console)**

2023-07-25 12:50 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [835280-MapsVideo](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3900/)<br/>**

2023-07-25 13:25 UTC, Sasikumar3595 commented on MAUI/Maps/shape-sublayer.md
> +To learn more about our .NET MAUI Maps layers, you can check the below video.
Above MAUI/Maps/legend.md topic and here specified the same content

To learn more about our .NET MAUI **Maps layers**,

2023-07-25 13:39 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [835280-MapsVideo](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3901/console)**

2023-07-25 13:40 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [835280-MapsVideo](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3901/)<br/>**

2023-07-25 13:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [835280-MapsVideo](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3902/console)**

2023-07-25 13:42 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [835280-MapsVideo](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3902/)<br/>**

2023-07-27 06:12 UTC, M-A32 requested changes

2023-07-27 06:12 UTC, M-A32 commented on MAUI/Maps/zoom-pan.md
> +To learn more about our .NET MAUI Maps zoom and pan, you can check the below video.
To learn more about the .NET MAUI Maps Zoom and Pan, you can check the following video.

2023-07-27 06:12 UTC, M-A32 commented on MAUI/Maps/tooltip.md
> +To learn more about our .NET MAUI Maps tooltip, you can check the below video.
To learn more about the .NET MAUI Maps tooltip, you can check the following video.

2023-07-27 06:12 UTC, M-A32 commented on MAUI/Maps/shape.md
> +To learn more about our .NET MAUI Maps layers, you can check the below video.
To learn more about the .NET MAUI Maps layers, you can check the following video.

2023-07-27 06:12 UTC, M-A32 commented on MAUI/Maps/markers.md
> +To learn more about our .NET MAUI Maps markers, you can check the below video.
To learn more about the .NET MAUI Maps markers, you can check the following video.

2023-07-27 06:12 UTC, M-A32 commented on MAUI/Maps/legend.md
> +To learn more about our .NET MAUI Maps legend, you can check the below video.
To learn more about the .NET MAUI Maps legend, you can check the following video.

2023-07-27 06:12 UTC, M-A32 commented on MAUI/Maps/data-labels.md
> +To learn more about our .NET MAUI Maps data labels, you can check the below video.
To learn more about the .NET MAUI Maps data labels, you can check the following video.

2023-07-27 06:12 UTC, M-A32 commented on MAUI/Maps/bubble.md
> +To learn more about our .NET MAUI Maps bubbles, you can check the below video.
To learn more about the .NET MAUI Maps bubbles, you can check the following video.

2023-07-27 11:05 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [835280-MapsVideo](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3929/console)**

2023-07-27 11:47 UTC, Sasikumar3595 commented on MAUI/Maps/tile-layer.md
> +To learn more about the .NET MAUI Maps layers, you can check the following video.
Specify tile layer

2023-07-27 11:48 UTC, Sasikumar3595 commented on MAUI/Maps/shape.md
> +To learn more about the .NET MAUI Maps layers, you can check the following video.
Specify the shape layer

2023-07-27 12:26 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [835280-MapsVideo](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3932/console)**

2023-07-27 12:26 UTC, IndumathiR-1995 commented on MAUI/Maps/tile-layer.md
> +To learn more about the .NET MAUI Maps layers, you can check the following video.
Specified layer to tile layer.

2023-07-27 12:26 UTC, IndumathiR-1995 commented on MAUI/Maps/shape.md
> +To learn more about the .NET MAUI Maps layers, you can check the following video.
Specified to shape layer.

2023-07-27 12:39 UTC, Sasikumar3595 approved these changes
Changes are fine

2023-07-28 03:40 UTC, Nijamudeen-Mohamed approved these changes

2023-07-28 03:40 UTC, merged