Added Sample for Selection and working-with-treeview
syncfusion-content/maui-docs pull request #1491
Opened 2023-09-13 05:56 UTC by SuthiYuvaraj

Added Sample for Selection and Working With TreeView UG

2023-09-13 05:56 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Selection](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4274/console)**

2023-09-13 05:57 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Selection](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4274/)<br/>**

2023-09-13 08:42 UTC, M-A32 requested changes
I have completed the review.

2023-09-13 08:42 UTC, M-A32 commented on MAUI/TreeView/working-with-treeview.md
> +description: Learn here all about Working with TreeView support in Syncfusion .NET MAUI TreeView (SfTreeView) control and more.
description: Learn here about Working with TreeView support in Syncfusion .NET MAUI TreeView (SfTreeView) control and more.

2023-09-13 08:42 UTC, M-A32 commented on MAUI/TreeView/working-with-treeview.md
> +The `ItemTapped` event will be triggered whenever tapping the item.  `ItemTappedEventArgs` has the following members which provides the information for `ItemTapped` event:
The `ItemTapped` event will be triggered whenever tapping the item.  `ItemTappedEventArgs` has the following members which provide the information for the `ItemTapped` event:

2023-09-13 08:42 UTC, M-A32 commented on MAUI/TreeView/selection.md
> +The `SelectionChanging` event is raised while selecting an item at the execution time. The `ItemSelectionChangingEventArgs` has the following members which provides the information for `SelectionChan
The `SelectionChanging` event is raised while selecting an item at the execution time. The `ItemSelectionChangingEventArgs` has the following members which provide the information for `SelectionChanging` event:

2023-09-13 08:42 UTC, M-A32 commented on MAUI/TreeView/selection.md
> +* `Single`: Allows selecting the single item only. When clicking on the selected item, selection not will not be cleared. This is the default value for `SelectionMode`.
* `Single`: Allows selecting the single item only. When clicking on the selected item, the selection will not be cleared. This is the default value for `SelectionMode`.

2023-09-13 08:42 UTC, M-A32 commented on MAUI/TreeView/selection.md
> +* `SingleDeselect`: Allows selecting the single item only. When clicking on the selected item, selection gets cleared.
* `SingleDeselect`: Allows selecting the single item only. When clicking on the selected item, the selection gets cleared.

2023-09-13 08:42 UTC, M-A32 commented on MAUI/TreeView/selection.md
> +* `Extended`: Allows to select the multiple items using the common key modifiers.
`Extended`: Allows to select multiple items using the common key modifiers.

2023-09-13 08:42 UTC, M-A32 commented on MAUI/TreeView/selection.md
> +The TreeView gets the selected item by using the `SelectedItem` properties. Both `SelectedItem` and `CurrentItem` returns the same data object when selecting single item. When selecting more than one
The TreeView gets the selected item by using the `SelectedItem` properties. Both `SelectedItem` and `CurrentItem` return the same data object when selecting a single item. When selecting more than one item, the `SelectedItem` property returns the first selected item, and the `CurrentItem` property returns the last selected item.

2023-09-13 08:42 UTC, M-A32 commented on MAUI/TreeView/selection.md
> +The `FocusBorderColor` property is used to set the border color for the current focused item.The default color is `Color.FromArgb("#000000")`.
The `FocusBorderColor` property is used to set the border color for the current focused item. The default color is `Color.FromArgb("#000000")`.

2023-09-13 10:08 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Selection](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4288/console)**

2023-09-13 10:09 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Selection](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4288/)<br/>**

2023-09-13 11:37 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Selection](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4317/)<br/>**

2023-09-13 13:20 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Selection](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4331/console)**

2023-09-13 13:21 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Selection](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4331/)<br/>**

2023-09-13 15:57 UTC, Lakshminatarajan commented
Include file path in the toc file

2023-09-13 15:58 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [Selection](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4348/console)**

2023-09-13 15:59 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Selection](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4348/console)**

2023-09-13 16:10 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Selection](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4348/)<br/>**

2023-09-14 02:20 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Selection](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4354/console)**

2023-09-14 02:21 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Selection](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4354/)<br/>**

2023-09-14 02:22 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Selection](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4355/console)**

2023-09-14 02:23 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Selection](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4355/)<br/>**

2023-09-14 04:46 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Selection](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4359/console)**

2023-09-14 04:46 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Selection](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4359/)<br/>**

2023-09-14 04:54 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Selection](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4361/console)**

2023-09-14 04:55 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Selection](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4361/)<br/>**

2023-09-14 05:20 UTC, SyncfusionBuild commented
The CI [Job](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4363/console) is already running for this Pull Request/Merge Approved with latest commit id. You cannot trigger the duplicate job for same.

2023-09-14 05:20 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [Selection](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4363/console)**

2023-09-14 05:22 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Selection](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4363/console)**

2023-09-14 05:24 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Selection](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4363/)<br/>**

2023-09-14 06:20 UTC, PiruthivirajM approved these changes

2023-09-14 06:21 UTC, merged