MAUI-846975-UG Update for SfDatePicker and SfTimePicker
syncfusion-content/maui-docs pull request #1496
Opened 2023-09-13 10:59 UTC by Sathish-087

**Description**
UG update for date and time picker.

2023-09-13 11:00 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-846975-DevDateTimePicker_UG](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4304/console)**

2023-09-13 11:46 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-846975-DevDateTimePicker_UG](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4318/console)**

2023-09-13 11:47 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-846975-DevDateTimePicker_UG](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4318/)<br/>**

2023-09-13 16:38 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-846975-DevDateTimePicker_UG](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4353/console)**

2023-09-13 16:42 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-846975-DevDateTimePicker_UG](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4353/)<br/>**

2023-09-14 08:08 UTC, M-A32 requested changes
Ì have completed the review.

2023-09-14 08:36 UTC, Sathish-087 commented on MAUI/DatePicker/date-interval.md
> +title: Date interval in .NET MAUI Date Picker control | Syncfusion
Content modified.

2023-09-14 08:37 UTC, Sathish-087 commented on MAUI/DatePicker/date-picker-mode.md
> +title: Date Picker mode in .NET MAUI Date Picker | Syncfusion
Content modified.

2023-09-14 08:40 UTC, Sathish-087 commented on MAUI/TimePicker/time-picker-mode.md
> +The [RelativePosition] is specified in the picker property enumeration, which is used to align the picker in a specific position. It provides eight position such as `AlignTop`, `AlignToLeftOf`, `Alig
Content modified.

2023-09-14 08:42 UTC, Sathish-087 commented on MAUI/TimePicker/time-picker-mode.md
> +The relative dialog mode is used to show the time picker in a pop up by setting the [Mode] property to [`RelativeDialog`]. It is used to align the picker in a specific position. You can set the posit
Content modified.

2023-09-14 08:43 UTC, Sathish-087 commented on MAUI/TimePicker/time-picker-mode.md
> +The dialog mode is used to show the time picker in a pop up by setting the [Mode] property to [`Dialog`] in [SfTimePicker].
Content modified.

2023-09-14 08:43 UTC, Sathish-087 commented on MAUI/TimePicker/formatting.md
> +title: Formatting in .NET MAUI Time Picker control | Syncfusion
Content modified.

2023-09-14 08:44 UTC, Sathish-087 commented on MAUI/TimePicker/formatting.md
> +Format is a way to represent the value of the time in a different string format. You can customize the time format by using the [Format] property in [PickerTimeFormat]. The default format is `HH_mm_s
Content modified.

2023-09-14 08:44 UTC, Sathish-087 commented on MAUI/DatePicker/date-picker-mode.md
> +title: Date Picker mode in .NET MAUI Date Picker Control | Syncfusion
Content modified.

2023-09-14 08:45 UTC, Sathish-087 commented on MAUI/DatePicker/date-picker-mode.md
> +Note: This property is automatically changed to `false` when you close the dialog by clicking outside of the it.
Content modified.

2023-09-14 08:46 UTC, Sathish-087 commented on MAUI/DatePicker/date-picker-mode.md
> +The relative dialog mode is used to display the date picker in a pop up by setting the [Mode] property to [`RelativeDialog`]. It is used to align the picker in a specific position. You can set the po
Content modified.

2023-09-14 08:47 UTC, Sathish-087 commented on MAUI/DatePicker/date-picker-mode.md
> +The [RelativePosition] is specified in the picker property enumeration, which is used to align the picker in a specific position. It provides eight position such as `AlignTop`, `AlignToLeftOf`, `Alig
Content modified.

2023-09-14 08:47 UTC, Sathish-087 commented on MAUI/DatePicker/date-picker-mode.md
> +Note: This property is automatically changed to `false` when you close the dialog by clicking outside of the it.
Content modified.

2023-09-14 08:48 UTC, Sathish-087 commented on MAUI/DatePicker/events.md
> +title: Date Picker events in .NET MAUI Date Picker Control | Syncfusion
Content modified.

2023-09-14 08:48 UTC, Sathish-087 commented on MAUI/DatePicker/events.md
> +* `EventArgs`: In Date Picker, the [DatePickerSelectionChangedEventArgs] is used for this event which holds the data of NewValue and OldValue.
Content modified.

2023-09-14 08:49 UTC, Sathish-087 commented on MAUI/DatePicker/events.md
> +* `EventArgs`: In SfDatePicker picker, [EventArgs] is used for this event.
Content modified.

2023-09-14 08:50 UTC, Sathish-087 commented on MAUI/DatePicker/events.md
> +    // If you need to close the picker, set IsOpen property to false.
Content modified.

2023-09-14 08:50 UTC, Sathish-087 commented on MAUI/DatePicker/events.md
> +* `EventArgs`: In SfDatePicker picker, [EventArgs] is used for this event.
Content modified.

2023-09-14 08:52 UTC, Sathish-087 commented on MAUI/DatePicker/events.md
> +* `EventArgs`: In SfDatePicker picker, [EventArgs] is used for this event.
Content modified.

2023-09-14 08:52 UTC, Sathish-087 commented on MAUI/DatePicker/events.md
> +    // This event is used to cancel the selected item in the Date picker.
Content modified.

2023-09-14 08:54 UTC, Sathish-087 commented on MAUI/TimePicker/events.md
> +* `EventArgs`: In SfTimePicker picker, the [TimePickerSelectionChangedEventArgs] is used for this event which holds the data of NewValue and OldValue.
Content modified.

2023-09-14 08:55 UTC, Sathish-087 commented on MAUI/TimePicker/events.md
> +* `EventArgs`: In SfTimePicker picker, [EventArgs] is used for this event.
Content modified.

2023-09-14 08:55 UTC, Sathish-087 commented on MAUI/TimePicker/events.md
> +    // If you need to open the picker, set IsOpen property to true.
Content modified.

2023-09-14 08:55 UTC, Sathish-087 commented on MAUI/TimePicker/events.md
> +* `EventArgs`: In SfTimePicker picker, [CancelEventArgs] is used to describe a cancel event which holds the bool value.
Content modified.

2023-09-14 08:56 UTC, Sathish-087 commented on MAUI/TimePicker/events.md
> +* `EventArgs`: In SfTimePicker picker, [EventArgs] is used for this event.
Content modified.

2023-09-14 08:56 UTC, Sathish-087 commented on MAUI/TimePicker/events.md
> +    // If you need to close the picker, set IsOpen property to false.
Content modified.

2023-09-14 08:57 UTC, Sathish-087 commented on MAUI/TimePicker/events.md
> +* `EventArgs`: In SfTimePicker picker, [EventArgs] is used for this event.
Content modified.

2023-09-14 08:57 UTC, Sathish-087 commented on MAUI/TimePicker/events.md
> +* `EventArgs`: In SfTimePicker picker, [EventArgs] is used for this event.
Content modified.

2023-09-14 08:58 UTC, Sathish-087 commented on MAUI/TimePicker/formatting.md
> +Format is a way to represent the time in a different string format. You can customize the time format by using the [Format] property in [PickerTimeFormat]. The default format is `HH_mm_ss`.
Content modified.

2023-09-14 08:58 UTC, Sathish-087 commented on MAUI/TimePicker/time-picker-mode.md
> +title: Time Picker modes in .NET MAUI Time Picker Control | Syncfusion
Content modified.

2023-09-14 08:59 UTC, Sathish-087 commented on MAUI/TimePicker/time-picker-mode.md
> +Note: This property is automatically changed to `false` when you close the dialog by clicking outside of the it.
Content modified.

2023-09-14 08:59 UTC, Sathish-087 commented on MAUI/TimePicker/time-picker-mode.md
> +Note: This property is automatically changed to `false` when you close the dialog by clicking outside of the it.
Content modified.

2023-09-14 09:00 UTC, Sathish-087 commented on MAUI/TimePicker/migration.md
> +<td>Occurs whenever the footer cancel button is clicked in time picker.</td>
Content modified.

2023-09-14 09:00 UTC, Sathish-087 commented on MAUI/TimePicker/migration.md
> +<td>Occurs whenever the footer ok button is clicked in time picker.</td>
Content modified.

2023-09-14 09:01 UTC, Sathish-087 commented on MAUI/TimePicker/migration.md
> +<td>Occurs whenever the selection changed on time picker. </td>
Content modified.

2023-09-14 09:01 UTC, Sathish-087 commented on MAUI/TimePicker/migration.md
> +<td>Occurs whenever the closing on time picker.</td>
Content modified.

2023-09-14 09:01 UTC, Sathish-087 commented on MAUI/TimePicker/migration.md
> +<td>Occurs whenever the closed on time picker.</td>
Content modified.

2023-09-14 09:01 UTC, Sathish-087 commented on MAUI/TimePicker/migration.md
> +<td>Occurs whenever the opened on time picker. </td>
Content modified.

2023-09-14 09:02 UTC, Sathish-087 commented on MAUI/TimePicker/migration.md
> +<td>Gets or sets the item height of the each item source.</td>
Content modified.

2023-09-14 09:02 UTC, Sathish-087 commented on MAUI/TimePicker/migration.md
> +<td>Gets or sets the value of header view. This property can be used to customize the of header in Time Picker.</td>
Content modified.

2023-09-14 09:03 UTC, Sathish-087 commented on MAUI/TimePicker/migration.md
> +<td>Gets or sets the value of footer view. This property can be used to customize the of Footer in TimePicker.</td>
Content modified.

2023-09-14 09:03 UTC, Sathish-087 commented on MAUI/TimePicker/migration.md
> +<td>Get or set the format that is used to change the format of SfTimePicker.</td>
Content modified.

2023-09-14 09:04 UTC, Sathish-087 commented on MAUI/TimePicker/migration.md
> +<td>Represents a selection view used to achieve time picker selection custom view.</td>
Content modified.

2023-09-14 09:05 UTC, Sathish-087 commented on MAUI/TimePicker/migration.md
> +<td>Represents a footer view used to achieve time picker footer custom view.</td>
Content modified.

2023-09-14 09:05 UTC, Sathish-087 commented on MAUI/TimePicker/migration.md
> +<td>Represents a header view used to achieve time picker header custom view.</td>
Content modified.

2023-09-14 09:05 UTC, Sathish-087 commented on MAUI/TimePicker/migration.md
> +<td>Represents a column header view used to achieve time picker header custom view.</td>
Content modified.

2023-09-14 09:07 UTC, Sathish-087 commented on MAUI/TimePicker/migration.md
> +To initialize the control, import the time picker namespace and initialize `SfTimePicker` as shown in the following code sample.
Content modified.

2023-09-14 09:08 UTC, Sathish-087 commented on MAUI/TimePicker/migration.md
> +To make the migration from the [Xamarin SfTimePicker](https://help.syncfusion.com/cr/xamarin/Syncfusion.XForms.Pickers.SfTimePicker.html) to [.NET MAUI SfTimePicker] easier, most of the APIs from the
Content modified.

2023-09-14 09:08 UTC, Sathish-087 commented on MAUI/DatePicker/migration.md
> +<td>Occurs whenever footer cancel button is clicked in date picker.</td>
Content modified.

2023-09-14 09:12 UTC, Sathish-087 commented on MAUI/DatePicker/migration.md
> +<td>Occurs whenever footer cancel button is clicked in date picker.</td>
Content modified.

2023-09-14 09:12 UTC, Sathish-087 commented on MAUI/DatePicker/migration.md
> +<td>Occurs whenever footer ok button is clicked in date picker.</td>
Content modified.

2023-09-14 09:12 UTC, Sathish-087 commented on MAUI/DatePicker/migration.md
> +<td>Gets or sets the item height of the each item source.</td>
Content modified.

2023-09-14 09:13 UTC, Sathish-087 commented on MAUI/DatePicker/migration.md
> +<td>Gets or sets the value of footer view. This property can be used to customize the of Footer in DatePicker.</td>
Content modified.

2023-09-14 09:13 UTC, Sathish-087 commented on MAUI/DatePicker/migration.md
> +<td>Gets or sets the value of header view. This property can be used to customize the of header in DatePicker.</td>
Content modified.

2023-09-14 09:22 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-846975-DevDateTimePicker_UG](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4395/)<br/>**

2023-09-14 09:37 UTC, Jeyasri-Murugan commented on maui-toc.html
> +            <li><a href="/maui/DatePicker/migration">Migration</a></li>
Migrate from Xamarin.Forms</a>

2023-09-14 09:38 UTC, Jeyasri-Murugan commented on maui-toc.html
> +            <li><a href="/maui/TimePicker/migration">Migration</a></li>
Migrate from Xamarin.Forms</a>

2023-09-14 09:41 UTC, Sathish-087 commented on maui-toc.html
> +            <li><a href="/maui/TimePicker/migration">Migration</a></li>
Content modified.

2023-09-14 09:42 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-846975-DevDateTimePicker_UG](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4396/console)**

2023-09-14 09:43 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-846975-DevDateTimePicker_UG](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4396/)<br/>**

2023-09-14 09:44 UTC, Jeyasri-Murugan approved these changes

2023-09-14 09:45 UTC, merged