860218 - Added UG documentation for new .NET MAUI  SfSwitch Control
syncfusion-content/maui-docs pull request #1727
Opened 2023-12-07 10:47 UTC by PriyadharshniM

Hi Team,

In this PR I have added UG document content for SfSwitch control. Please review and merge the same.

Regards,
Priyadharshni M

2023-12-07 10:48 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_SfSwitch](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4751/console)**

2023-12-07 10:49 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [UG_SfSwitch](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4751/)<br/>**

2023-12-07 12:51 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_SfSwitch](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4756/console)**

2023-12-07 14:11 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_SfSwitch](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4761/console)**

2023-12-07 14:11 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [UG_SfSwitch](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4761/)<br/>**

2023-12-07 15:17 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [UG_SfSwitch](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4763/)<br/>**

2023-12-08 06:32 UTC, M-A32 requested changes
I have completed the review.

2023-12-09 14:10 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_SfSwitch](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4772/console)**

2023-12-09 14:11 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [UG_SfSwitch](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4772/)<br/>**

2023-12-09 14:16 UTC, PriyadharshniM commented on MAUI/Switch/states.md
> +The disabled indeterminate state can be enabled when you need to display the work progress. The below code example demonstrates loading the switch in disabled indeterminate state by setting [`IsOn`]
I've updated all the contents.

2023-12-11 08:12 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_SfSwitch](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4780/console)**

2023-12-11 08:12 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [UG_SfSwitch](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4780/)<br/>**

2023-12-12 05:36 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_SfSwitch](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4801/console)**

2023-12-12 05:38 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [UG_SfSwitch](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4801/)<br/>**

2023-12-12 05:57 UTC, Choza-rajan commented on MAUI/Switch/Events.md
> +sfSwitch.StateChanged += SfSwitch_StateChanged;
Remove the StateChanged in here

2023-12-12 07:39 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_SfSwitch](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4807/console)**

2023-12-12 07:40 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [UG_SfSwitch](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4807/)<br/>**

2023-12-12 10:19 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_SfSwitch](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4813/console)**

2023-12-12 10:21 UTC, PriyadharshniM commented on MAUI/Switch/Events.md
> +sfSwitch.StateChanged += SfSwitch_StateChanged;
Removed StateChanged

2023-12-12 10:21 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [UG_SfSwitch](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4813/)<br/>**

2023-12-13 05:28 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [UG_SfSwitch](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4827/console)**

2023-12-13 05:37 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_SfSwitch](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4827/console)**

2023-12-13 05:39 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [UG_SfSwitch](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4827/)<br/>**

2023-12-13 12:55 UTC, Choza-rajan approved these changes

2023-12-13 12:57 UTC, merged