MAUI PDF Viewer UG changes for 2023 Volume 4 release
syncfusion-content/maui-docs pull request #1740
Opened 2023-12-12 14:23 UTC by Deepak1799

2023-12-12 14:24 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MyDevelopment](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4820/console)**

2023-12-12 14:25 UTC, Vikassekar approved these changes

2023-12-12 14:26 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MyDevelopment](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4820/)<br/>**

2023-12-12 14:35 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MyDevelopment](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4821/console)**

2023-12-12 14:36 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MyDevelopment](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4821/)<br/>**

2023-12-12 15:46 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MyDevelopment](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4822/console)**

2023-12-12 15:47 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MyDevelopment](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4823/console)**

2023-12-12 15:49 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MyDevelopment](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4823/)<br/>**

2023-12-12 17:15 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [MyDevelopment](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4824/console)**

2023-12-12 17:17 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MyDevelopment](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4824/console)**

2023-12-12 17:21 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4824/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2023-12-12 17:33 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MyDevelopment](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4825/)<br/>**

2023-12-13 04:53 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MyDevelopment](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4826/console)**

2023-12-13 04:54 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MyDevelopment](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4826/)<br/>**

2023-12-13 07:29 UTC, M-A32 requested changes
I have completed the review.

2023-12-13 07:29 UTC, M-A32 commented on MAUI/PDF-Viewer/Shapes.md
> +You can draw and add shape annotations to a PDF document interactively by touch (or mouse down) and drag. The following steps explains how to draw circle shape annotation on a PDF. Similarly, you can
You can interactively draw and add shape annotations to a PDF document by touching or dragging the mouse down. The following steps explain how to draw a circle-shaped annotation on a PDF. Similarly, you can draw other shapes like arrows, lines, and rectangles.

2023-12-13 09:00 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MyDevelopment](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4842/console)**

2023-12-13 09:04 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MyDevelopment](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4843/console)**

2023-12-13 09:05 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MyDevelopment](https://jenkins.syncfusion.com/job/Content/job/maui-docs/4843/)<br/>**

2023-12-13 09:17 UTC, merged