MAUI-849605 Updated Polar Chart UG page in .NET MAUI
syncfusion-content/maui-docs pull request #1972
Opened 2024-03-11 06:28 UTC by snehakPV

**Feature Description**

Updated UG for Polar Chart (new control).

**Analysis and Design**

Referred the Xamarin, WinUI and WPF UG
Xamarin - https://help.syncfusion.com/xamarin/charts/charttypes#polar-chart
WinUI - https://help.syncfusion.com/winui/polar-chart/overview
WPF - https://help.syncfusion.com/wpf/charts/seriestypes/radarandpolar

**Solution Description**

This UG document helps to guide the user to understand the feature.

**Updated Files**

	1. Migrate from Xamarin.Forms
	2. Axis
		○ Types
		○ Title
		○ Axis Labels
		○ Grid Lines
		○ Tick Lines
		○ Axis Line
	3.  Chart Types
		○ Polar Area Chart
		○ Polar Line Chart
	4. Appearance
	5. Data Label
	6. Tooltip
	7. Exporting
	8. Get the touch position in chart
	9. Transform axis value to pixel value and vice versa

2024-03-12 09:58 UTC, florenceliliana requested changes
The content review is completed.

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/Axis/Axislabels.md
> +title: Axis labels in .NET MAUI Chart control | Syncfusion
title: Axis Labels in .NET MAUI Chart Control | Syncfusion

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/Axis/Axisline.md
> +The polar chart axis provides support for customizing the style of the axis line by defining the [AxisLineStyle]()property, as shown in the code snippet below.
The polar chart axis provides support for customizing the style of the axis line by defining the [AxisLineStyle]()property, as shown in the code sample below.

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/Axis/Gridlines.md
> +title: Axis grid lines in .NET MAUI Chart control | Syncfusion
title: Axis Grid Lines in .NET MAUI Chart Control | Syncfusion

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/Axis/Overview.md
> +title: About Axis in .NET MAUI Chart control | Syncfusion
title: About Axis in .NET MAUI Chart Control | Syncfusion

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/Axis/Overview.md
> +* It allows you to customize the chart axis line, including grid lines and tick lines. You can also customize the style of the axis line by defining the [AxisLineStyle]().
* It allows you to customize the chart axis line, including grid lines, and tick lines. You can also customize the style of the axis line by defining the [AxisLineStyle]().

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/Axis/Ticklines.md
> +title: Axis Tick Line in .NET MAUI Chart control | Syncfusion
title: Axis Tick Line in .NET MAUI Chart Control | Syncfusion

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/Axis/Ticklines.md
> +Both major and minor tick lines can be customized by using the [MajorTickStyle]() and [MinorTickStyle]() properties respectively. They provide options to change the [StrokeWidth](), [TickSize](), [St
Both major and minor tick lines can be customized using the [MajorTickStyle]() and [MinorTickStyle]() properties respectively. They provide options to change the [StrokeWidth](), [TickSize](), [Stroke]() of tick lines. By default, minor tick lines will not be visible.

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/Axis/Title.md
> +title: Title for axis in .NET MAUI Chart control | Syncfusion
title: Title for axis in .NET MAUI Chart Control | Syncfusion

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/Axis/Types.md
> +title: Axis types in .NET MAUI Chart control | Syncfusion
title: Axis types in .NET MAUI Chart Control | Syncfusion

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/Axis/Types.md
> +In [DateTimeAxis](), intervals can be customized by using the [Interval]() and [IntervalType]() properties. For example, setting [Interval]() as 6 and [IntervalType]() as [Months]() will consider 6 m
In [DateTimeAxis](), intervals can be customized using the [Interval]() and [IntervalType]() properties. For example, setting [Interval]() as 6 and [IntervalType]() as [Months]() will consider 6 months as interval.

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/Axis/Types.md
> +Axis can be inverted by using the [IsInversed]() property. The default value of this property is `False`.
Axis can be inverted using the [IsInversed]() property. The default value of this property is `False`.

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/DataLabels.md
> +title: Data labels in .NET MAUI Chart control | Syncfusion
title: Data Labels in .NET MAUI Chart Control | Syncfusion

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/DataLabels.md
> +Data labels can be customized by using the [DataLabelSettings]() property of chart series. To customize them, you need to create an instance of [PolarDataLabelSettings]() and set it to the [DataLabel
Data labels can be customized using the [DataLabelSettings]() property of chart series. To customize them, you need to create an instance of [PolarDataLabelSettings]() and set it to the [DataLabelSettings]() property. The following properties available in [PolarDataLabelSettings]() can be used to customize the data labels.

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/DataLabels.md
> +* [BarAlignment]() - Gets or sets the data label alignment top, middle or bottom.
* [BarAlignment]() - Gets or sets the data label alignment top, middle, or bottom.

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/DataLabels.md
> +* [LabelPlacement]() - Gets or sets the data label position inside, outside or default.
* [LabelPlacement]() - Gets or sets the data label position inside, outside, or default.

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/DataLabels.md
> +The alignment of data labels inside the series is defined by using the [BarAlignment]() property.
The alignment of data labels inside the series is defined using the [BarAlignment]() property.

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/DataLabels.md
> +The [LabelPlacement]() property is used to position the data labels at [Center](), [Inner]() and [Outer]() positions relative to the actual data point position. By default, labels are positioned base
The [LabelPlacement]() property is used to position the data labels at [Center](), [Inner](), and [Outer]() positions relative to the actual data point position. By default, labels are positioned based on the series types for better readability.

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/DataLabels.md
> +The [SfPolarChart]() provides support to customize the appearance of the datalabel by using the [LabelTemplate]() property.
The [SfPolarChart]() provides support to customize the appearance of the datalabel using the [LabelTemplate]() property.

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/Exporting.md
> +title: Exporting in .NET MAUI Chart control | Syncfusion
title: Exporting in .NET MAUI Chart Control | Syncfusion

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/Exporting.md
> +The following code snippet demonstrates the usage of this method:
The following code sample demonstrates the usage of this method:

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/Exporting.md
> +**Windows Phone, Android and MAC** – The image will be saved inside the 'Pictures' directory of the file system.
**Windows Phone, Android, and MAC** – The image will be saved inside the 'Pictures' directory of the file system.

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/Exporting.md
> +The following code snippet demonstrates the usage of this method:
The following code sample demonstrates the usage of this method:

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/Get-the-touch-position-in-chart.md
> +title: Get the touch position in Syncfusion SfPolarChart
title: Get the Touch Position in Syncfusion SfPolarChart

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/PolarArea.md
> +title: Polar Area Chart in .NET MAUI Chart control | Syncfusion
title: Polar Area Chart in .NET MAUI Chart Control | Syncfusion

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/PolarArea.md
> +The [GridLineType]() property used to modify the rendering style of axis grid lines. The default [GridLineType]() is [Circle](). Switching to the [Polygon]() grid line type transforms the polar chart
The [GridLineType]() property used to modify the rendering style of axis grid lines. The default [GridLineType]() is [Circle](). Switching to the [Polygon]() grid line type transforms the polar chart appearance, resembling a spider, or web chart.

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/PolarArea.md
> +The [IsClosed]() property used to render the series with or without closed path. The default value of [IsClosed]() is true.
The [IsClosed]() property is used to render the series with or without closed path. The default value of [IsClosed]() is true.

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/PolarLine.md
> +title: Polar Line Chart in .NET MAUI Chart control | Syncfusion
title: Polar Line Chart in .NET MAUI Chart Control | Syncfusion

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/PolarLine.md
> +To display an line series in a polar chart, instantiate the [PolarLineSeries]() and include it in the [Series]() collection property of [SfPolarChart]().
To display a line series in a polar chart, instantiate the [PolarLineSeries]() and include it in the [Series]() collection property of [SfPolarChart]().

2024-03-12 09:58 UTC, florenceliliana commented on MAUI/Polar-Charts/PolarLine.md
> +The [IsClosed]() property used to render the series with or without closed path. The default value of [IsClosed]() is true.
The [IsClosed]() property is used to render the series with or without closed path. The default value of [IsClosed]() is true.

2024-03-12 10:34 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-849605_UG_Polar_Chart](https://ci.syncfusion.com/job/Content/job/maui-docs/642/console)**

2024-03-12 10:35 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/642/artifact/cireports/)<br/>Build Location: [MAUI-849605_UG_Polar_Chart](https://ci.syncfusion.com/job/Content/job/maui-docs/642/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/642/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [1](https://ci.syncfusion.com/job/Content/job/maui-docs/642/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/642/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/642/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/maui-docs/642/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/642/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/642/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/642/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-13 09:56 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-849605_UG_Polar_Chart](https://ci.syncfusion.com/job/Content/job/maui-docs/788/console)**

2024-03-13 09:57 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-849605_UG_Polar_Chart](https://ci.syncfusion.com/job/Content/job/maui-docs/788/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/788/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/788/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/788/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/788/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/788/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/788/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/788/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/788/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-13 10:33 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-849605_UG_Polar_Chart](https://ci.syncfusion.com/job/Content/job/maui-docs/798/console)**

2024-03-13 10:34 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/798/artifact/cireports/)<br/>Build Location: [MAUI-849605_UG_Polar_Chart](https://ci.syncfusion.com/job/Content/job/maui-docs/798/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/798/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/798/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/798/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/798/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/maui-docs/798/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/798/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/798/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/798/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-13 10:47 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-849605_UG_Polar_Chart](https://ci.syncfusion.com/job/Content/job/maui-docs/805/console)**

2024-03-13 10:53 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/805/artifact/cireports/)<br/>Build Location: [MAUI-849605_UG_Polar_Chart](https://ci.syncfusion.com/job/Content/job/maui-docs/805/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/805/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/805/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/805/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/805/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/maui-docs/805/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/805/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/805/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/805/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-13 10:58 UTC, Saravanan-Madhesh approved these changes
Changes fine

2024-03-13 11:33 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/814/artifact/cireports/)<br/>Build Location: [MAUI-849605_UG_Polar_Chart](https://ci.syncfusion.com/job/Content/job/maui-docs/814/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/814/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/814/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/814/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/814/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/maui-docs/814/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/814/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/814/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/814/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-13 11:56 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-849605_UG_Polar_Chart](https://ci.syncfusion.com/job/Content/job/maui-docs/828/console)**

2024-03-13 12:02 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-849605_UG_Polar_Chart](https://ci.syncfusion.com/job/Content/job/maui-docs/828/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/828/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/828/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/828/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/828/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/828/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/828/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/828/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/828/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-13 12:02 UTC, merged