Added RadialMenu content.
syncfusion-content/maui-docs pull request #1987
Opened 2024-03-12 05:20 UTC by prakashKannanSf3972

2024-03-12 05:21 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [UG_RadialMenu](https://ci.syncfusion.com/job/Content/job/maui-docs/562/console)**

2024-03-12 05:31 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_RadialMenu](https://ci.syncfusion.com/job/Content/job/maui-docs/562/console)**

2024-03-12 06:22 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_RadialMenu](https://ci.syncfusion.com/job/Content/job/maui-docs/569/console)**

2024-03-12 06:39 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_RadialMenu](https://ci.syncfusion.com/job/Content/job/maui-docs/571/console)**

2024-03-12 06:45 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/571/artifact/cireports/)<br/>Build Location: [UG_RadialMenu](https://ci.syncfusion.com/job/Content/job/maui-docs/571/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/571/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [1](https://ci.syncfusion.com/job/Content/job/maui-docs/571/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/571/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/571/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [12](https://ci.syncfusion.com/job/Content/job/maui-docs/571/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](https://ci.syncfusion.com/job/Content/job/maui-docs/571/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/571/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/571/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-12 06:56 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_RadialMenu](https://ci.syncfusion.com/job/Content/job/maui-docs/575/console)**

2024-03-12 06:58 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/575/artifact/cireports/)<br/>Build Location: [UG_RadialMenu](https://ci.syncfusion.com/job/Content/job/maui-docs/575/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/575/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [1](https://ci.syncfusion.com/job/Content/job/maui-docs/575/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/575/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/575/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [12](https://ci.syncfusion.com/job/Content/job/maui-docs/575/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/575/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/575/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/575/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-12 07:02 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_RadialMenu](https://ci.syncfusion.com/job/Content/job/maui-docs/580/console)**

2024-03-12 07:05 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/maui-docs/580/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-03-12 07:05 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: Not Started :x:<br/>Build Location: [UG_RadialMenu](https://ci.syncfusion.com/job/Content/job/maui-docs/580/)<br/>**

2024-03-12 07:06 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [UG_RadialMenu](https://ci.syncfusion.com/job/Content/job/maui-docs/583/console)**

2024-03-12 07:08 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_RadialMenu](https://ci.syncfusion.com/job/Content/job/maui-docs/583/console)**

2024-03-12 07:13 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/maui-docs/583/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-03-12 07:13 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: FAILURE :x:<br/>Build Location: [UG_RadialMenu](https://ci.syncfusion.com/job/Content/job/maui-docs/583/)<br/>**

2024-03-12 07:14 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [UG_RadialMenu](https://ci.syncfusion.com/job/Content/job/maui-docs/590/console)**

2024-03-12 07:22 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_RadialMenu](https://ci.syncfusion.com/job/Content/job/maui-docs/590/console)**

2024-03-12 07:35 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/590/artifact/cireports/)<br/>Build Location: [UG_RadialMenu](https://ci.syncfusion.com/job/Content/job/maui-docs/590/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/590/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/590/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/590/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/590/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [4](https://ci.syncfusion.com/job/Content/job/maui-docs/590/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/590/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/590/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/590/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-12 13:20 UTC, M-A32 requested changes
I have completed the review.

2024-03-12 13:20 UTC, M-A32 commented on MAUI/Radial-Menu/Overview.md
> +`Custom segments` : Complete customization options for the menu and its items, such as coloring, sizing,palcement and shapes, using the segmentation option.
`Custom segments` : Complete customization options for the menu and its items, such as coloring, sizing, placement, and shapes, using the segmentation option.

2024-03-12 13:20 UTC, M-A32 commented on MAUI/Radial-Menu/Place-And-Drag-RadialMenu.md
> +* [`Position`](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.SfRadialMenu.DragBeginEventArgs.html#Syncfusion_Maui__SfRadialMenu_DragBeginEventArgs_Position) - Gets the Start position of the Rad
* [`Position`](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.SfRadialMenu.DragBeginEventArgs.html#Syncfusion_Maui__SfRadialMenu_DragBeginEventArgs_Position) - Gets the Start position of the RadialMenu.

2024-03-12 13:20 UTC, M-A32 commented on MAUI/Radial-Menu/Place-And-Drag-RadialMenu.md
> +* [`OldValue`](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.SfRadialMenu.DragEndEventArgs.html#Syncfusion_Maui_SfRadialMenu_DragEndEventArgs_OldValue) - Gets the Start position of the RadialMe
* [`OldValue`](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.SfRadialMenu.DragEndEventArgs.html#Syncfusion_Maui_SfRadialMenu_DragEndEventArgs_OldValue) - Gets the Start position of the RadialMenu.

2024-03-12 13:20 UTC, M-A32 commented on MAUI/Radial-Menu/Place-And-Drag-RadialMenu.md
> +* [`NewValue`](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.SfRadialMenu.DragEndEventArgs.html#Syncfusion_Maui_SfRadialMenu_DragEndEventArgs_NewValue) - Gets the ens position of the RadialMenu
* [`NewValue`](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.SfRadialMenu.DragEndEventArgs.html#Syncfusion_Maui_SfRadialMenu_DragEndEventArgs_NewValue) - Gets the end position of the RadialMenu.

2024-03-12 13:20 UTC, M-A32 commented on MAUI/Radial-Menu/Populating-Items.md
> +title: Populating Items in MAUI Radial Menu control | Syncfusion
title: Populating Items in MAUI Radial Menu Control | Syncfusion

2024-03-12 13:20 UTC, M-A32 commented on MAUI/Radial-Menu/Populating-Items.md
> +The following code snippet demonstrates how to Create a RadialMenu control with Items having the given text.
The following code sample demonstrates how to Create a RadialMenu control with Items having the given text.

2024-03-12 13:20 UTC, M-A32 commented on MAUI/Radial-Menu/Populating-Items.md
> +The following code snippet demonstrates how to Display images and text in the RadialMenu items of the control.
The following code sample demonstrates how to Display images and text in the RadialMenu items of the control.

2024-03-12 13:20 UTC, M-A32 commented on MAUI/Radial-Menu/Populating-Items.md
> +The following code snippet demonstrates how to Display custom font with text in the RadialMenu items of the control.
The following code sample demonstrates how to Display custom font with text in the RadialMenu items of the control.

2024-03-12 13:20 UTC, M-A32 commented on MAUI/Radial-Menu/Populating-Items.md
> +The following code snippet demonstrates how to add the nested items of radial menu.
The following code sample demonstrates how to add the nested items of radial menu.

2024-03-12 14:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_RadialMenu](https://ci.syncfusion.com/job/Content/job/maui-docs/694/console)**

2024-03-12 14:49 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/694/artifact/cireports/)<br/>Build Location: [UG_RadialMenu](https://ci.syncfusion.com/job/Content/job/maui-docs/694/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/694/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/694/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/694/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/694/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [6](https://ci.syncfusion.com/job/Content/job/maui-docs/694/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/694/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/694/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/694/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-12 15:24 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_RadialMenu](https://ci.syncfusion.com/job/Content/job/maui-docs/695/console)**

2024-03-12 15:25 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/695/artifact/cireports/)<br/>Build Location: [UG_RadialMenu](https://ci.syncfusion.com/job/Content/job/maui-docs/695/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/695/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/695/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/695/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/695/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [4](https://ci.syncfusion.com/job/Content/job/maui-docs/695/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/695/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/695/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/695/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-12 15:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_RadialMenu](https://ci.syncfusion.com/job/Content/job/maui-docs/697/console)**

2024-03-12 15:51 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/697/artifact/cireports/)<br/>Build Location: [UG_RadialMenu](https://ci.syncfusion.com/job/Content/job/maui-docs/697/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/697/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/697/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/697/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/697/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [4](https://ci.syncfusion.com/job/Content/job/maui-docs/697/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/697/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/697/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/697/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-13 06:00 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_RadialMenu](https://ci.syncfusion.com/job/Content/job/maui-docs/748/console)**

2024-03-13 06:01 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/748/artifact/cireports/)<br/>Build Location: [UG_RadialMenu](https://ci.syncfusion.com/job/Content/job/maui-docs/748/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/748/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/748/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/748/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/748/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [4](https://ci.syncfusion.com/job/Content/job/maui-docs/748/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/748/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/748/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/748/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-13 09:12 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_RadialMenu](https://ci.syncfusion.com/job/Content/job/maui-docs/774/console)**

2024-03-13 09:59 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_RadialMenu](https://ci.syncfusion.com/job/Content/job/maui-docs/789/console)**

2024-03-13 10:07 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [UG_RadialMenu](https://ci.syncfusion.com/job/Content/job/maui-docs/789/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/789/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/789/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/789/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/789/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/789/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/789/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/789/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/789/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-13 11:14 UTC, Choza-rajan approved these changes

2024-03-13 11:14 UTC, merged