UG for Custom-Bookmark feature
syncfusion-content/maui-docs pull request #2007
Opened 2024-03-12 16:14 UTC by SalmanBaris25

UG for Custom-Bookmark feature

2024-03-12 16:15 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [CustomBookmark](https://ci.syncfusion.com/job/Content/job/maui-docs/700/console)**

2024-03-12 16:21 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/700/artifact/cireports/)<br/>Build Location: [CustomBookmark](https://ci.syncfusion.com/job/Content/job/maui-docs/700/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/700/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [1](https://ci.syncfusion.com/job/Content/job/maui-docs/700/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/700/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/700/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/700/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/700/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/700/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/700/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-12 16:22 UTC, NavaneethS commented on MAUI/PDF-Viewer/Custom-Bookmark.md
> +A PDF document may optionally have custom bookmarks that allow the user to bookmark pages and navigate them. The PDF viewer control displays these custom bookmarks in a list of page elements.
navigate to them. 
"list of page elements"?

2024-03-12 16:22 UTC, NavaneethS commented on MAUI/PDF-Viewer/Custom-Bookmark.md
> +To access the custom bookmarks, you can use the `CustomBookmarks` collection. This property provides a list of custom booknarks.
the list of custom bookmarks in the PDF.

2024-03-12 16:23 UTC, NavaneethS commented on MAUI/PDF-Viewer/Custom-Bookmark.md
> +Bookmark bookmarkToEdit = pdfViewer.CustomBookmarks.FirstOrDefault(b => b.Title == "Bookmark to Edit");
GIve a more meaning name such as "Chapter 2"

2024-03-12 16:24 UTC, NavaneethS commented on MAUI/PDF-Viewer/Custom-Bookmark.md
> +    bookmarkToEdit.PageNumber = 1; // Change the page index
PageNumber cannot be set.

2024-03-12 16:28 UTC, NavaneethS commented on MAUI/PDF-Viewer/Custom-Bookmark.md
> +As mentioned above, you can show the outline view by setting the `IsOultineViewVisible` property to `true`. When the outline view is showing, you can tap on any bookmark to navigate to the destinatio
"pointed to"

2024-03-12 16:42 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [CustomBookmark](https://ci.syncfusion.com/job/Content/job/maui-docs/704/console)**

2024-03-12 16:43 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [CustomBookmark](https://ci.syncfusion.com/job/Content/job/maui-docs/704/console)**

2024-03-12 16:46 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/maui-docs/704/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-03-12 16:46 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: Not Started :x:<br/>Build Location: [CustomBookmark](https://ci.syncfusion.com/job/Content/job/maui-docs/704/)<br/>**

2024-03-12 16:47 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/maui-docs/706/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-03-12 16:48 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [CustomBookmark](https://ci.syncfusion.com/job/Content/job/maui-docs/707/console)**

2024-03-12 16:54 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [CustomBookmark](https://ci.syncfusion.com/job/Content/job/maui-docs/707/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/707/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/707/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/707/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/707/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/707/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/707/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/707/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/707/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-12 16:57 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [CustomBookmark](https://ci.syncfusion.com/job/Content/job/maui-docs/709/console)**

2024-03-12 16:58 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/maui-docs/709/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-03-12 16:58 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: Not Started :x:<br/>Build Location: [CustomBookmark](https://ci.syncfusion.com/job/Content/job/maui-docs/709/)<br/>**

2024-03-12 16:59 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [CustomBookmark](https://ci.syncfusion.com/job/Content/job/maui-docs/710/console)**

2024-03-12 17:00 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/maui-docs/710/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-03-12 17:01 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [CustomBookmark](https://ci.syncfusion.com/job/Content/job/maui-docs/712/console)**

2024-03-12 17:03 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [CustomBookmark](https://ci.syncfusion.com/job/Content/job/maui-docs/712/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/712/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/712/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/712/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/712/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/712/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/712/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/712/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/712/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-13 04:03 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [CustomBookmark](https://ci.syncfusion.com/job/Content/job/maui-docs/723/console)**

2024-03-13 04:04 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [CustomBookmark](https://ci.syncfusion.com/job/Content/job/maui-docs/723/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/723/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/723/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/723/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/723/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/723/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/723/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/723/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/723/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-13 04:14 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [CustomBookmark](https://ci.syncfusion.com/job/Content/job/maui-docs/724/console)**

2024-03-13 04:15 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [CustomBookmark](https://ci.syncfusion.com/job/Content/job/maui-docs/724/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/724/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/724/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/724/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/724/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/724/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/724/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/724/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/724/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-13 09:21 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [CustomBookmark](https://ci.syncfusion.com/job/Content/job/maui-docs/776/console)**

2024-03-13 09:23 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [CustomBookmark](https://ci.syncfusion.com/job/Content/job/maui-docs/776/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/776/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/776/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/776/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/776/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/776/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/776/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/776/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/776/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-13 13:28 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [CustomBookmark](https://ci.syncfusion.com/job/Content/job/maui-docs/840/console)**

2024-03-13 13:29 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [CustomBookmark](https://ci.syncfusion.com/job/Content/job/maui-docs/840/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/840/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/840/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/840/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/840/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/840/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/840/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/840/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/840/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-13 13:33 UTC, NavaneethS approved these changes

2024-03-13 13:33 UTC, merged

2024-03-13 14:00 UTC, M-A32 requested changes
I have completed the review.

2024-03-13 14:00 UTC, M-A32 commented on MAUI/PDF-Viewer/Custom-Bookmark.md
> +//Get the required custom bookmark
//Get the required custom bookmark.

2024-03-13 14:00 UTC, M-A32 commented on MAUI/PDF-Viewer/Custom-Bookmark.md
> +The PDF viewer allows the users to navigate to an custom bookmark using the `GoToBookmark` method. The below code snippet illustrates the same.
The PDF viewer allows the users to navigate to an custom bookmark using the `GoToBookmark` method. The following code sample illustrates the same.

2024-03-13 14:00 UTC, M-A32 commented on MAUI/PDF-Viewer/Custom-Bookmark.md
> +Tap the context menu button on the custom bookmark to be edited and choose Rename and enter the desired name.
Tap the context menu button on the custom bookmark to be edited and then choose Rename and enter the desired name.

2024-03-13 14:00 UTC, M-A32 commented on MAUI/PDF-Viewer/Custom-Bookmark.md
> +title: Custom Bookmark in .NET MAUI PDF Viewer control | Syncfusion
title: Custom Bookmark in .NET MAUI PDF Viewer Control | Syncfusion