871811 - Added UG contents for MAUI TreeMap control
syncfusion-content/maui-docs pull request #2042
Opened 2024-03-14 04:33 UTC by Kerubananthan3761

### Description ###

Added UG content for the following topics for Maui TreeMap control:

2024-03-14 04:33 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/896/console)**

2024-03-14 04:35 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/maui-docs/896/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-03-14 04:35 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: Not Started :x:<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/896/)<br/>**

2024-03-14 04:36 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/898/console)**

2024-03-14 04:52 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/898/console)**

2024-03-14 04:55 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/898/artifact/cireports/)<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/898/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/898/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/898/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/898/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/898/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/maui-docs/898/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](https://ci.syncfusion.com/job/Content/job/maui-docs/898/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/898/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/898/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-14 07:19 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/925/console)**

2024-03-14 07:19 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/925/artifact/cireports/)<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/925/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/925/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/925/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/925/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/925/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/maui-docs/925/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](https://ci.syncfusion.com/job/Content/job/maui-docs/925/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/925/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/925/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-14 08:35 UTC, Karthickmani97 commented on MAUI/TreeMap/getting-started.md
> +* The `RangeColorValuePath` specifies the name of the property within the data object that provides the range color value for each item in the tree map.This range color value typically represents a q
Mention legend and applicable for Treemap range.

2024-03-14 09:10 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/maui-docs/933/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-03-14 09:11 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: Not Started :x:<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/933/)<br/>**

2024-03-14 09:11 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/935/console)**

2024-03-14 09:12 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/935/console)**

2024-03-14 09:13 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/935/artifact/cireports/)<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/935/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/935/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/935/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/935/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/935/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/maui-docs/935/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](https://ci.syncfusion.com/job/Content/job/maui-docs/935/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/935/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/935/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-14 10:52 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/962/console)**

2024-03-14 13:38 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/1003/console)**

2024-03-14 13:46 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/1003/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1003/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1003/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1003/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1003/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1003/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1003/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1003/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1003/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-15 05:50 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/1045/console)**

2024-03-15 05:51 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/1045/artifact/cireports/)<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/1045/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1045/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1045/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1045/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1045/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/maui-docs/1045/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1045/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1045/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1045/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-15 07:11 UTC, Karthickmani97 commented on MAUI/TreeMap/levels.md
> +Levels in .NET MAUI TreeMap allow for hierarchical data visualization, enabling multi-level categorization and exploration of complex datasets. You can seamlessly navigate through different levels of
You can seamlessly navigate through different levels of data hierarchy, facilitating comprehensive understanding and analysis.

Seems like drill down support.

2024-03-15 07:13 UTC, Karthickmani97 commented on MAUI/TreeMap/levels.md
> +## TreeMap Level
rename to group path

2024-03-15 07:17 UTC, Karthickmani97 commented on MAUI/TreeMap/levels.md
> +
In the following example, three levels are added and each level is configured using the GroupPath.

2024-03-15 07:21 UTC, Karthickmani97 commented on MAUI/TreeMap/levels.md
> +## Level customization
Customize level appearance

2024-03-15 07:24 UTC, Karthickmani97 commented on MAUI/TreeMap/levels.md
> +The .NET MAUI TreeMap control allows you to customize the background, text style, spacing, and more.
The level appearance customization can be achieved by using the `TextStyle`, `Background`, `Spacing`, `Stroke,` and `StrokeWidth` properties of `TreeMapLevel` in the `SfTreeMap.`

2024-03-15 07:25 UTC, Karthickmani97 commented on MAUI/TreeMap/levels.md
> +### Customize the levels spacing
Customize level appearance using spacing

2024-03-15 07:29 UTC, Karthickmani97 commented on MAUI/TreeMap/levels.md
> +Customize the spacing between the tree map header items using the `Spacing` property of `TreeMapLevel`. The default value of `Spacing` property is `1`.
The `Spacing` property can be customized by using the `TreeMapLevel` of `SfTreeMap.` It is used to customize the the spacing between the tree map header items and its default value of `Spacing` property is `1.`

2024-03-15 07:59 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/1066/console)**

2024-03-15 08:00 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/1066/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1066/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1066/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1066/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1066/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1066/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1066/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1066/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1066/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-15 08:40 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/1069/console)**

2024-03-15 08:41 UTC, Karthickmani97 commented on MAUI/TreeMap/selection-and-highlights.md
> +The Treemap control allows interactive selection of items by clicking or tapping. `Tooltip`, if enabled, displays additional information upon clicking or tapping, enhancing user understanding of data
The Treemap control allows to select a specific group or item to distinguish it from others. When enabled, the Tooltip feature displays additional information during interaction. However, when SelectionMode is set to None, interaction is disabled for treemap items.

2024-03-15 08:44 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/1069/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1069/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1069/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1069/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1069/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1069/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1069/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1069/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1069/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-15 08:49 UTC, Karthickmani97 commented on MAUI/TreeMap/selection-and-highlights.md
> +With `Single` selection mode, you can choose one item at a time within the Treemap control, ideal for isolating and examining individual data points thoroughly.
In the Single selection mode, users can choose one item at a time within the Treemap control.

2024-03-15 08:53 UTC, Karthickmani97 commented on MAUI/TreeMap/selection-and-highlights.md
> +With `Multiple` selection mode you can select multiple items simultaneously, facilitating comparative analysis and exploration of related data within the Treemap.
In the Multiple selection mode, users can select multiple items simultaneously within the Treemap control.

2024-03-15 08:55 UTC, Karthickmani97 commented on MAUI/TreeMap/selection-and-highlights.md
> +When set to none selection mode, interactivity within the Treemap control is disabled.
In the None selection mode, interaction with treemap items is disabled.

2024-03-15 09:11 UTC, Karthickmani97 commented on MAUI/TreeMap/selection-and-highlights.md
> +## Customize selected item border color
Customize selected item appearence

The selected items appearance customization can be achieved by using the SelectedItemStroke and SelectedItemStrokeWidth properties in the SfTreeMap.

2024-03-15 09:12 UTC, M-A32 requested changes
I have completed the review.

2024-03-15 09:12 UTC, M-A32 commented on MAUI/TreeMap/levels.md
> +The `Background` property of `TreeMapLevel` can be customized by using the `Levels` in the `SfTreeMap.` It is used to customize the background brush for the tree map header item. The default value of
The `Background` property of `TreeMapLevel` can be customized by using the `Levels` in the `SfTreeMap.` It is used to customize the background brush for the treemap header item. The default value of `Background` is `Null.`

2024-03-15 09:12 UTC, M-A32 commented on MAUI/TreeMap/levels.md
> +N> Setting a background value for the property applies the same background color to tree map header items within the same level. To customize the background color for both header and leaf items at ea
N> Setting a background value for the property applies the same background color to treemap header items within the same level. To customize the background color for both header and leaf items at each level, utilize the `GroupItemBrushSettings` property.

2024-03-15 09:12 UTC, M-A32 commented on MAUI/TreeMap/levels.md
> +The `Stroke` property of `TreeMapLevel` can be customized by using the `Levels` in the `SfTreeMap.` It is used to customize the stroke color for the tree map header item. The default value of `Stroke
The `Stroke` property of `TreeMapLevel` can be customized using the `Levels` in the `SfTreeMap.` It is used to customize the stroke color for the treemap header item. The default value of `Stroke` is `new SolidColorBrush(Color.FromArgb("#CAC4D0")).`

2024-03-15 09:12 UTC, M-A32 commented on MAUI/TreeMap/levels.md
> +The `StrokeWidth` property of `TreeMapLevel` can be customized by using the `Levels` in the `SfTreeMap.` It is used to customize the width of the stroke for the tree map header item. The default valu
The `StrokeWidth` property of `TreeMapLevel` can be customized by using the `Levels` in the `SfTreeMap.` It is used to customize the width of the stroke for the treemap header item. The default value of `StrokeWidth` is `1.`

2024-03-15 09:12 UTC, M-A32 commented on MAUI/TreeMap/levels.md
> +The `TextStyle` property of `TreeMapLevel` can be customized by using the `Levels` in the `SfTreeMap.` It is used to customize the `TextColor,` `FontSize,` `FontFamily` and `FontAttributes.` of tree
The `TextStyle` property of `TreeMapLevel` can be customized using the `Levels` in the `SfTreeMap.` It is used to customize the `TextColor,` `FontSize,` `FontFamily` and `FontAttributes.` of treemap header item text.

2024-03-15 09:12 UTC, M-A32 commented on MAUI/TreeMap/selection-and-highlights.md
> +title: Selection and highlights in .NET MAUI TreeMap | Syncfusion
title: Selection and Highlights in .NET MAUI TreeMap | Syncfusion

2024-03-15 09:12 UTC, M-A32 commented on MAUI/TreeMap/selection-and-highlights.md
> +Selection mode in the Treemap control determines the interactivity level, enabling users to choose specific items by clicking or tapping. The default value of `SelectionMode` is `SelectionMode.Single
The selection mode in the Treemap control determines the interactivity level, enabling users to choose specific items by clicking or tapping. The default value of `SelectionMode` is `SelectionMode.Single`.

2024-03-15 09:12 UTC, M-A32 commented on MAUI/TreeMap/selection-and-highlights.md
> +You can programmatically add default selected items by utilizing the `SelectedItems` property of `SfTreeMap`. This property holds a collection of tree map items representing the currently selected on
You can programmatically add default selected items by utilizing the `SelectedItems` property of `SfTreeMap`. This property holds a collection of tree map items representing the currently selected ones. In the `Single` selection mode, only the first item in the SelectedItems collection will be selected. In the `Multiple` selection mode, all items in the SelectedItems collection will be selected. When `SelectionMode` is set to `None`, no items will be selected automatically.

2024-03-15 09:12 UTC, M-A32 commented on MAUI/TreeMap/selection-and-highlights.md
> +Customize the selected item border color using `SelectedItemStroke` property of `SfTreeMap`. The default value of `SelectedItemStroke` is `Color.FromArgb("#1C1B1F")`.
Customize the selected item border color using the `SelectedItemStroke` property of `SfTreeMap`. The default value of `SelectedItemStroke` is `Color.FromArgb("#1C1B1F")`.

2024-03-15 09:12 UTC, M-A32 commented on MAUI/TreeMap/selection-and-highlights.md
> +Customize selected item border thickness using `SelectedItemStrokeWidth` property of `SfTreeMap`. The default value of `SelectedItemStrokeWidth` is `2`.
Customize selected item border thickness using the `SelectedItemStrokeWidth` property of `SfTreeMap`. The default value of `SelectedItemStrokeWidth` is `2`.

2024-03-15 09:40 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/1072/console)**

2024-03-15 09:44 UTC, Karthickmani97 commented on MAUI/TreeMap/leaf-item-settings.md
> +The `LabelPath` property within the `TreeMapLeafItemSettings` is used to display text for the leaf items. This property allows you to specify the path to the data property containing the text you wan
A leaf item represents a visualized data element in the TreeMap. It does not contain child items but may have a parent item if levels are specified in the TreeMap control.

2024-03-15 09:51 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/1072/artifact/cireports/)<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/1072/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1072/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1072/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1072/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1072/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/maui-docs/1072/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1072/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1072/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1072/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-15 09:56 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/1073/console)**

2024-03-15 10:05 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/1073/console)**

2024-03-15 10:08 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/1073/artifact/cireports/)<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/1073/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1073/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1073/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1073/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1073/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/maui-docs/1073/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1073/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1073/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1073/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-15 10:13 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/1077/console)**

2024-03-15 10:13 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/1077/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1077/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1077/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1077/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1077/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1077/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1077/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1077/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1077/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-15 10:18 UTC, karthikraja-arumugam approved these changes

2024-03-15 10:28 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/1079/console)**

2024-03-15 10:30 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/1079/artifact/cireports/)<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/1079/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1079/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1079/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1079/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1079/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1079/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](https://ci.syncfusion.com/job/Content/job/maui-docs/1079/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1079/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1079/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-15 10:36 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/1081/console)**

2024-03-15 10:38 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [871811-Maui-TreeMap-contents](https://ci.syncfusion.com/job/Content/job/maui-docs/1081/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1081/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1081/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1081/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1081/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1081/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1081/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1081/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1081/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-15 10:42 UTC, merged