Show row header UG
syncfusion-content/maui-docs pull request #2254
Opened 2024-05-14 08:12 UTC by AbhishekSF4201

Added show row header

2024-05-14 08:13 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ShowRowHeaderUG](https://ci.syncfusion.com/job/Content/job/maui-docs/1518/console)**

2024-05-14 08:21 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ShowRowHeaderUG](https://ci.syncfusion.com/job/Content/job/maui-docs/1518/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1518/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1518/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1518/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1518/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1518/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1518/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1518/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1518/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-05-31 04:25 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/maui-docs/1634/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-05-31 04:25 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: Not Started :x:<br/>Build Location: [ShowRowHeaderUG](https://ci.syncfusion.com/job/Content/job/maui-docs/1634/)<br/>**

2024-05-31 04:26 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ShowRowHeaderUG](https://ci.syncfusion.com/job/Content/job/maui-docs/1635/console)**

2024-05-31 04:27 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ShowRowHeaderUG](https://ci.syncfusion.com/job/Content/job/maui-docs/1635/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1635/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1635/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1635/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1635/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1635/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1635/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1635/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1635/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-05-31 05:21 UTC, ashok-kuvaraja requested changes

2024-05-31 05:21 UTC, ashok-kuvaraja commented on MAUI/DataGrid/Column-types.md
> +The `SfDataGrid` allows you to add the content inside the row header using the RowHeaderTemplate. It allows you to load any view inside the row header.
The row header is a type of column that is placed as the first cell of each row and remains frozen. To enable the row header, set `SfDataGrid.ShowRowHeader` to `true`.

Additionally, the `SfDataGrid` allows you to customize the row header width using the `SfDataGrid.RowHeaderWidth` property. The default value is 25.

2024-05-31 05:21 UTC, ashok-kuvaraja commented on MAUI/DataGrid/Column-types.md
> +### Show row header
Row header

2024-05-31 05:21 UTC, ashok-kuvaraja commented on MAUI/DataGrid/conditional-styling.md
> +## Show row header
Row header

2024-05-31 05:21 UTC, ashok-kuvaraja commented on MAUI/DataGrid/styling.md
> +### Styling show row header
Styling row header

2024-05-31 05:21 UTC, ashok-kuvaraja commented on MAUI/DataGrid/styling.md
> +The row header can be customized by the writing style for DataGridRowHeaderCell Target Type.
The row header can be customized by the writing style for `DataGridRowHeaderCell` Target Type

2024-05-31 07:15 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ShowRowHeaderUG](https://ci.syncfusion.com/job/Content/job/maui-docs/1644/console)**

2024-05-31 07:15 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/maui-docs/1644/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-05-31 07:16 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: FAILURE :x:<br/>Build Location: [ShowRowHeaderUG](https://ci.syncfusion.com/job/Content/job/maui-docs/1644/)<br/>**

2024-05-31 07:16 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ShowRowHeaderUG](https://ci.syncfusion.com/job/Content/job/maui-docs/1645/console)**

2024-05-31 07:17 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/maui-docs/1645/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-05-31 07:17 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: FAILURE :x:<br/>Build Location: [ShowRowHeaderUG](https://ci.syncfusion.com/job/Content/job/maui-docs/1645/)<br/>**

2024-05-31 07:18 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ShowRowHeaderUG](https://ci.syncfusion.com/job/Content/job/maui-docs/1647/console)**

2024-05-31 07:24 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ShowRowHeaderUG](https://ci.syncfusion.com/job/Content/job/maui-docs/1647/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1647/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1647/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1647/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1647/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1647/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1647/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1647/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1647/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-05-31 07:31 UTC, ashok-kuvaraja requested changes

2024-05-31 07:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ShowRowHeaderUG](https://ci.syncfusion.com/job/Content/job/maui-docs/1649/console)**

2024-05-31 07:42 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ShowRowHeaderUG](https://ci.syncfusion.com/job/Content/job/maui-docs/1649/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1649/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1649/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1649/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1649/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1649/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1649/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1649/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1649/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-05-31 07:52 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ShowRowHeaderUG](https://ci.syncfusion.com/job/Content/job/maui-docs/1650/console)**

2024-05-31 09:12 UTC, AbhishekSF4201 commented
This implementation has done in another pull request.
https://github.com/syncfusion-content/maui-docs/pull/2300/

2024-05-31 09:12 UTC, closed without merging