890255 - Create a UG Document for Built-In Toolbar
syncfusion-content/maui-docs pull request #2353
Opened 2024-06-10 13:21 UTC by Bharathi4332

Added the Missing API reference links , updated the localization and themes files

2024-06-10 13:22 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [BuiltInToolbar](https://ci.syncfusion.com/job/Content/job/maui-docs/1850/console)**

2024-06-10 13:32 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [BuiltInToolbar](https://ci.syncfusion.com/job/Content/job/maui-docs/1850/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1850/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1850/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1850/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1850/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1850/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1850/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1850/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1850/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-06-10 16:59 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [BuiltInToolbar](https://ci.syncfusion.com/job/Content/job/maui-docs/1857/console)**

2024-06-10 17:19 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [BuiltInToolbar](https://ci.syncfusion.com/job/Content/job/maui-docs/1857/console)**

2024-06-10 17:20 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: FAILURE :x:<br/>Build Location: [BuiltInToolbar](https://ci.syncfusion.com/job/Content/job/maui-docs/1857/)<br/>**

2024-06-10 17:30 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [BuiltInToolbar](https://ci.syncfusion.com/job/Content/job/maui-docs/1861/console)**

2024-06-10 17:31 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: FAILURE :x:<br/>Build Location: [BuiltInToolbar](https://ci.syncfusion.com/job/Content/job/maui-docs/1861/)<br/>**

2024-06-10 17:37 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [BuiltInToolbar](https://ci.syncfusion.com/job/Content/job/maui-docs/1866/console)**

2024-06-10 17:38 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: FAILURE :x:<br/>Build Location: [BuiltInToolbar](https://ci.syncfusion.com/job/Content/job/maui-docs/1866/)<br/>**

2024-06-11 03:25 UTC, kannans24 commented
rebuild

2024-06-11 03:26 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [BuiltInToolbar](https://ci.syncfusion.com/job/Content/job/maui-docs/1881/console)**

2024-06-11 03:27 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/1881/artifact/cireports/)<br/>Build Location: [BuiltInToolbar](https://ci.syncfusion.com/job/Content/job/maui-docs/1881/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1881/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1881/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1881/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1881/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [2](https://ci.syncfusion.com/job/Content/job/maui-docs/1881/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1881/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1881/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1881/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-06-11 07:05 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [BuiltInToolbar](https://ci.syncfusion.com/job/Content/job/maui-docs/1893/console)**

2024-06-11 07:08 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [BuiltInToolbar](https://ci.syncfusion.com/job/Content/job/maui-docs/1893/console)**

2024-06-11 07:13 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/1893/artifact/cireports/)<br/>Build Location: [BuiltInToolbar](https://ci.syncfusion.com/job/Content/job/maui-docs/1893/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1893/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1893/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1893/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1893/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [2](https://ci.syncfusion.com/job/Content/job/maui-docs/1893/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1893/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1893/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1893/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-06-11 07:28 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [BuiltInToolbar](https://ci.syncfusion.com/job/Content/job/maui-docs/1896/console)**

2024-06-11 07:29 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/1896/artifact/cireports/)<br/>Build Location: [BuiltInToolbar](https://ci.syncfusion.com/job/Content/job/maui-docs/1896/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1896/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1896/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1896/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1896/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [2](https://ci.syncfusion.com/job/Content/job/maui-docs/1896/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1896/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1896/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1896/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-06-11 08:06 UTC, Deepak1799 requested changes
Requested changes

2024-06-11 08:06 UTC, Deepak1799 commented on MAUI/PDF-Viewer/Built-In-Toolbar.md
> +The [SfPdfViewer](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.PdfViewer.SfPdfViewer.html) has a built-in toolbar, which allows you to perform operations such as adding, modifying annotations,
<img width="225" alt="image" src="https://github.com/syncfusion-content/maui-docs/assets/65169077/97388e0d-e1e2-418f-bb0a-09cbc89686b4">

Use different word for this

2024-06-11 08:06 UTC, Deepak1799 commented on MAUI/PDF-Viewer/Built-In-Toolbar.md
> +### Customizing toolbar items using the GetByName method
Why continuously 3 header types are used?

2024-06-11 08:06 UTC, Deepak1799 commented on MAUI/PDF-Viewer/Built-In-Toolbar.md
> +### Adding a New Toolbar Item
**### Adding a New Toolbar Item**

In contents header, only the first letter of the first word should be in **caps**, others are need to be in the small casing.

**Ensure address this in all the areas**

<img width="789" alt="image" src="https://github.com/syncfusion-content/maui-docs/assets/65169077/5bc19e88-f1e8-4c00-8969-c93918239339">

2024-06-11 08:06 UTC, Deepak1799 commented on MAUI/PDF-Viewer/Built-In-Toolbar.md
> +To add an item to the toolbar in [SfPdfViewer](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.PdfViewer.SfPdfViewer.html), first, create the button you want to include. Then, convert that button
Generalise the item or say it as an example.

<img width="339" alt="image" src="https://github.com/syncfusion-content/maui-docs/assets/65169077/218b19b6-b07f-4c79-8909-948a55ed7d6b">

In the above contents, it conveys only button can be added as item.

2024-06-11 08:06 UTC, Deepak1799 commented on MAUI/PDF-Viewer/Built-In-Toolbar.md
> +### Mobile Toolbar Name :
**### Mobile Toolbar Name**

It should be mentioned in plural. Please correct

2024-06-11 08:33 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [BuiltInToolbar](https://ci.syncfusion.com/job/Content/job/maui-docs/1900/console)**

2024-06-11 08:37 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [BuiltInToolbar](https://ci.syncfusion.com/job/Content/job/maui-docs/1900/console)**

2024-06-11 08:40 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/1900/artifact/cireports/)<br/>Build Location: [BuiltInToolbar](https://ci.syncfusion.com/job/Content/job/maui-docs/1900/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1900/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1900/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1900/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1900/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [2](https://ci.syncfusion.com/job/Content/job/maui-docs/1900/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1900/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1900/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1900/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-06-11 10:27 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [BuiltInToolbar](https://ci.syncfusion.com/job/Content/job/maui-docs/1925/console)**

2024-06-11 10:28 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/1925/artifact/cireports/)<br/>Build Location: [BuiltInToolbar](https://ci.syncfusion.com/job/Content/job/maui-docs/1925/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1925/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1925/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1925/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1925/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/maui-docs/1925/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [2](https://ci.syncfusion.com/job/Content/job/maui-docs/1925/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1925/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1925/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-06-11 10:43 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [BuiltInToolbar](https://ci.syncfusion.com/job/Content/job/maui-docs/1927/console)**

2024-06-11 10:44 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [BuiltInToolbar](https://ci.syncfusion.com/job/Content/job/maui-docs/1927/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1927/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1927/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1927/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1927/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1927/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1927/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1927/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1927/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-06-11 10:45 UTC, Bharathi4332 commented
I have addressed the feedback

2024-06-11 12:08 UTC, VikramDevaraj31 commented on MAUI/PDF-Viewer/Toolbar.md
> +## Show/hide the built-in toolbar
Built-In Toolbar => Toolbar

2024-06-11 12:15 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [BuiltInToolbar](https://ci.syncfusion.com/job/Content/job/maui-docs/1934/console)**

2024-06-11 12:26 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [BuiltInToolbar](https://ci.syncfusion.com/job/Content/job/maui-docs/1934/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1934/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1934/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1934/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1934/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1934/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1934/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1934/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/1934/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-06-11 12:29 UTC, Deepak1799 approved these changes
Approved the changes

2024-06-11 12:29 UTC, merged