initial commit
syncfusion-content/maui-docs pull request #2508
Opened 2024-07-18 10:18 UTC by AbhishekSF4201

2024-07-22 04:00 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [IncrementalLoading](https://ci.syncfusion.com/job/Content/job/maui-docs/2280/console)**

2024-07-22 04:02 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/2280/artifact/cireports/)<br/>Build Location: [IncrementalLoading](https://ci.syncfusion.com/job/Content/job/maui-docs/2280/)<br/>Technical Error(s): 0<br/>Spelling Error(s): [1](https://ci.syncfusion.com/job/Content/job/maui-docs/2280/artifact/cireports/spellcheck/spellcheckreport.htm)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2280/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2280/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2280/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2280/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/maui-docs/2280/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2280/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2280/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2280/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-07-22 04:07 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [IncrementalLoading](https://ci.syncfusion.com/job/Content/job/maui-docs/2281/console)**

2024-07-22 04:08 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/2281/artifact/cireports/)<br/>Build Location: [IncrementalLoading](https://ci.syncfusion.com/job/Content/job/maui-docs/2281/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2281/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2281/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2281/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2281/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/maui-docs/2281/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2281/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2281/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2281/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-07-23 05:33 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [IncrementalLoading](https://ci.syncfusion.com/job/Content/job/maui-docs/2294/console)**

2024-07-23 05:34 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/2294/artifact/cireports/)<br/>Build Location: [IncrementalLoading](https://ci.syncfusion.com/job/Content/job/maui-docs/2294/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2294/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2294/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2294/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2294/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/maui-docs/2294/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2294/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2294/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2294/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-07-23 05:38 UTC, ashok-kuvaraja requested changes

2024-07-23 06:00 UTC, AbhishekSF4201 commented on MAUI/DataGrid/Column-types.md
> +### Drop down width
changed the title.

2024-07-23 06:00 UTC, AbhishekSF4201 commented on MAUI/DataGrid/Column-types.md
> +The ComboBox control include a `DropDownWidth` that allows the user to increase the width of the drop down box.
changed the content

2024-07-23 06:48 UTC, AbhishekSF4201 commented on MAUI/DataGrid/Column-types.md
> +The `CanFilterSuggestion` property in the SfComboBox component is used to enable or disable the filtering of suggestions based on user input. When set to `true`, this property allows the combo box to
done

2024-07-23 06:52 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/2296/artifact/cireports/)<br/>Build Location: [IncrementalLoading](https://ci.syncfusion.com/job/Content/job/maui-docs/2296/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2296/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2296/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2296/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2296/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/maui-docs/2296/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2296/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2296/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2296/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-07-23 12:13 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [IncrementalLoading](https://ci.syncfusion.com/job/Content/job/maui-docs/2305/console)**

2024-07-23 12:23 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/maui-docs/2305/artifact/cireports/)<br/>Build Location: [IncrementalLoading](https://ci.syncfusion.com/job/Content/job/maui-docs/2305/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2305/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2305/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2305/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2305/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/maui-docs/2305/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2305/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2305/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2305/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-07-23 12:41 UTC, ashok-kuvaraja requested changes

2024-07-23 12:41 UTC, ashok-kuvaraja commented on MAUI/DataGrid/performance.md
> +In the below code, `IncrementalList` is initialized by passing Action to its constructor for loading items incrementally.
The DataGrid supports loading data incrementally using the `ISupportIncrementalLoading` interface. This interface includes the `LoadMoreItemsAsync` method, which helps to load data incrementally. The `LoadMoreItemsAsync` method is called on-demand while scrolling, based on the `HasMoreItems` property.

If `HasMoreItems` is false, SfDataGrid stops calling `LoadMoreItemsAsync`. SfDataGrid includes `IncrementalList`, which is derived from `ISupportIncrementalLoading`. You can use `IncrementalList` or create a collection derived from `ISupportIncrementalLoading` and bind it to `SfDataGrid.ItemsSource`.

Additionally, the `SfDataGrid.DataFetchSize` property defines the count argument in the `LoadMoreItemsAsync` method, which determines the amount of data to be loaded into the items source when the user reaches the end of the `SfDataGrid`

In the code below, `IncrementalList` is initialized by passing an Action to its constructor for loading items incrementally.

2024-07-23 12:48 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [IncrementalLoading](https://ci.syncfusion.com/job/Content/job/maui-docs/2308/console)**

2024-07-23 12:50 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [IncrementalLoading](https://ci.syncfusion.com/job/Content/job/maui-docs/2308/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2308/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2308/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2308/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2308/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2308/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2308/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2308/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2308/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-07-23 12:55 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [IncrementalLoading](https://ci.syncfusion.com/job/Content/job/maui-docs/2309/console)**

2024-07-23 13:02 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [IncrementalLoading](https://ci.syncfusion.com/job/Content/job/maui-docs/2310/console)**

2024-07-23 13:04 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [IncrementalLoading](https://ci.syncfusion.com/job/Content/job/maui-docs/2310/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2310/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2310/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2310/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2310/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2310/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2310/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2310/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/maui-docs/2310/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-07-23 13:06 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [IncrementalLoading](https://ci.syncfusion.com/job/Content/job/maui-docs/2311/console)**

2024-07-23 13:07 UTC, ashok-kuvaraja approved these changes
The changes are fine.

2024-07-23 13:49 UTC, merged