MAUI-2365 Added UG documentation for Signaturepad control
syncfusion-content/maui-docs pull request #346
Opened 2022-06-17 19:28 UTC by PraveenGopalsamy

Hi Team,

I have added Ug documentation for the SignaturePad control. In that, I have explained the following features,
* Overview
* Getting started
    * Initializing
    * Stroke color customization
    * Stroke thickness customization
    * ToImageSource() and Clear() methods
    * Events - DrawStarted and DrawCompleted.
Please review the content and merge this PR.

Regards,
Praveen G.

2022-06-17 19:29 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1339/artifact/cireports/)<br/>Build Location: [MAUI-2365-Signature-pad-UG-content](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1339/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1339/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [2](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1339/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1339/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1339/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1339/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1339/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-20 06:32 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-2365-Signature-pad-UG-content](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1341/console)**

2022-06-20 06:34 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1341/artifact/cireports/)<br/>Build Location: [MAUI-2365-Signature-pad-UG-content](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1341/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1341/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1341/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1341/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1341/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1341/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1341/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-20 06:35 UTC, MeikandaNayanar requested changes

2022-06-20 06:59 UTC, PraveenGopalsamy commented on MAUI/SignaturePad/getting-started.md
> +            .ConfigureSyncfusionCore()
No need. I have removed that.

2022-06-20 07:35 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-2365-Signature-pad-UG-content](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1342/console)**

2022-06-20 09:22 UTC, MeikandaNayanar requested changes

2022-06-20 09:46 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-2365-Signature-pad-UG-content](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1343/console)**

2022-06-20 09:47 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1343/artifact/cireports/)<br/>Build Location: [MAUI-2365-Signature-pad-UG-content](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1343/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1343/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1343/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1343/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1343/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1343/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1343/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-20 10:22 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-2365-Signature-pad-UG-content](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1348/console)**

2022-06-20 10:23 UTC, PraveenGopalsamy commented on MAUI/SignaturePad/getting-started.md
> +Import the `SfSignaturePad` namespace and initialize the signature pad as shown below.
Yes updated throughout whole documentation.

2022-06-20 10:45 UTC, merged