MAUI-2361 Added UG documentation for Slider edge labels placement support
syncfusion-content/maui-docs pull request #347
Opened 2022-06-20 09:47 UTC by PraveenGopalsamy

Hi Team,

I have added Ug documentation for the Sliders(SfSlider, SfRangeSlider, and SfRangeSelector) edge label placement feature. Please review the content and merge this PR.

Regards,
Praveen G.

2022-06-20 10:46 UTC, MeikandaNayanar approved these changes

2022-06-20 10:47 UTC, MeikandaNayanar approved these changes

2022-06-20 11:26 UTC, PraveenGopalsamy commented
rebuild

2022-06-20 11:27 UTC, PraveenGopalsamy commented
rebuild

2022-06-20 11:27 UTC, SyncfusionBuild commented
The CI [Job](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1350/console) is already running for this Pull Request/Merge Approved with latest commit id. You cannot trigger the duplicate job for same.

2022-06-20 13:04 UTC, PraveenGopalsamy commented
rebuild

2022-06-20 13:05 UTC, SyncfusionBuild commented
The CI [Job](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1351/console) is already running for this Pull Request/Merge Approved with latest commit id. You cannot trigger the duplicate job for same.

2022-06-20 13:05 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-2361-Sliders-edge-label-placement](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1351/console)**

2022-06-21 06:28 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-2361-Sliders-edge-label-placement](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1353/console)**

2022-06-21 06:33 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-2361-Sliders-edge-label-placement](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1353/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1353/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1353/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1353/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1353/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1353/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1353/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-21 06:35 UTC, MeikandaNayanar requested changes

2022-06-21 06:35 UTC, MeikandaNayanar commented on MAUI/Range-Selector/labels.md
> +The `EdgeLabelsPlacement` property is used to move the first and last label either inside the track bounds or on the intervals. The default value of the `EdgeLabelsPlacement` property is `SliderEdgeL
based on the intervals

2022-06-21 06:41 UTC, PraveenGopalsamy commented on MAUI/Range-Selector/labels.md
> +The `EdgeLabelsPlacement` property is used to move the first and last label either inside the track bounds or on the intervals. The default value of the `EdgeLabelsPlacement` property is `SliderEdgeL
Updated as mentioned.

2022-06-21 06:42 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-2361-Sliders-edge-label-placement](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1354/console)**

2022-06-21 06:43 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-2361-Sliders-edge-label-placement](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1354/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1354/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1354/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1354/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1354/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1354/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1354/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-21 07:14 UTC, MeikandaNayanar approved these changes

2022-06-21 09:49 UTC, merged