MAUI-2438 DataGrid selection UG
syncfusion-content/maui-docs pull request #413
Opened 2022-07-01 10:45 UTC by FarjanaParveen

DataGrid selection UG

2022-07-01 10:46 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-2438_SelectionDataGrid](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1590/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1590/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1590/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1590/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1590/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1590/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1590/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-07-04 10:36 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-2438_SelectionDataGrid](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1618/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1618/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1618/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1618/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1618/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1618/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1618/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-07-06 13:42 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-2438_SelectionDataGrid](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1670/console)**

2022-07-06 13:43 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-2438_SelectionDataGrid](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1670/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1670/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1670/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1670/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1670/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1670/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1670/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-07-07 06:48 UTC, NeelakandanKannan requested changes
I have added my feedback as comments. Get back to me with the changes.

2022-07-07 06:48 UTC, NeelakandanKannan commented on MAUI/DataGrid/selection.md
> +<td> Allows selection of a single row or cell only. Upon selecting the next row or cell, the selection in the previous row or cell is cleared. </td>
@FarjanaParveen  - remove the **"cell only"** content.

2022-07-07 06:48 UTC, NeelakandanKannan commented on MAUI/DataGrid/selection.md
> +<td> Allows selection of more than one row or cell. Selection is not cleared when selecting more than one row or cell. When you click on an already selected row or cell for the second time, the selec
@FarjanaParveen  - Remove the "or cell" content.

2022-07-07 06:48 UTC, NeelakandanKannan commented on MAUI/DataGrid/selection.md
> +`SfDataGrid` provides [SelectedIndex] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.SfDataGrid.html#Syncfusion_Maui_DataGrid_SfDataGrid_SelectedIndex), [SelectedRow] (https://help.syn
@FarjanaParveen  - Include the SelectedRows property too in this para.

2022-07-07 06:48 UTC, NeelakandanKannan commented on MAUI/DataGrid/selection.md
> +`SfDataGrid.SelectedIndex`: Provides the row index of SfDataGrid.SelectedItem. Denotes the index of first selected row in multiple selection.
SfDataGrid.SelectedItem - This is wrong API right?

2022-07-07 06:48 UTC, NeelakandanKannan commented on MAUI/DataGrid/selection.md
> +### Process selection using methods
@FarjanaParveen  - Change the title as,

Select all the rows

2022-07-07 06:48 UTC, NeelakandanKannan commented on MAUI/DataGrid/selection.md
> +![SelectionAll in .NET MAUI DataGrid](Images/selection/maui-datagrid-selectall.png)
Alt text may be

All the rows selected in .NET MAUI DataGrid

2022-07-07 06:48 UTC, NeelakandanKannan commented on MAUI/DataGrid/selection.md
> +The data grid provides the following events for selection:
@FarjanaParveen  - Don't split datagrid word.

2022-07-07 06:48 UTC, NeelakandanKannan commented on MAUI/DataGrid/selection.md
> +[SelectionChanging] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.SfDataGrid.html#Syncfusion_Maui_DataGrid_SfDataGrid_SelectionChanging): This event is raised while selecting a row at
@FarjanaParveen  - Put the api reference link for Cancel and DataGridSelectionChangingEventArgs.

2022-07-07 06:48 UTC, NeelakandanKannan commented on MAUI/DataGrid/selection.md
> +These two events are triggered with DataGridSelectionChangingEventArgs and DataGridSelectionChangedEventArgs that contain the following properties:
@FarjanaParveen  - Put the backtik for APIs.

2022-07-07 06:48 UTC, NeelakandanKannan commented on MAUI/DataGrid/selection.md
> +{% highlight c# tabtitle="MainPage.xaml.cs" %}
@FarjanaParveen  = file name should be ViewModel.cs. Provide the full class implementation.

2022-07-07 08:29 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-2438_SelectionDataGrid](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1681/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1681/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1681/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1681/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1681/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1681/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1681/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-07-07 09:02 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-2438_SelectionDataGrid](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1682/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1682/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1682/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1682/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1682/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1682/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1682/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +Moves the current cell to next to the active current cell. If the CurrentCell is in last cell, pressing <kbd>RightArrow</kbd> does nothing.
Moves the current cell next to the active current cell. If the CurrentCell is in the last cell, pressing the <kbd>RightArrow</kbd> does nothing.

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +The SfDataGrid will be scrolled to next set of rows that are not displayed in view, including the row that are partially displayed and the current cell is set to last row.
The SfDataGrid will be scrolled to the next set of rows that are not displayed in the view, including the row that is partially displayed and the current cell is set to the last row.

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +The SfDataGrid will be scrolled to previous set of rows that are not displayed in view, including the row that are partially displayed and the current cell is set to the first row.
The SfDataGrid will be scrolled to the previous set of rows that are not displayed in the view, including the row that is partially displayed and the current cell is set to the first row.

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +Moves the current cell to next to the active current cell. If the active current cell is the last cell of the current row, the focus will moved to first cell of the row next to the current row.If the
Moves the current cell next to the active current cell. If the active current cell is the last cell of the current row, the focus will be moved to the first cell of the row next to the current row. If the active current cell is the last cell of the last row, the focus will be moved to the next control in the tab order of the parent container.

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +Moves the current cell to previous to the active current cell. If the active current cell is the first cell of the current row, the current cell will moved to last cell of the row previous to the cur
Moves the current cell to previous to the active current cell. If the active current cell is the first cell of the current row, the current cell will be moved to the last cell of the row previous to the current row. If the active current cell is the first cell of the first row, the focus will be moved to the previous control in the tab order of the parent container.

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +If the active current cell is in edit mode, the changes will committed and moves the current cell to below the active current cell. If the active current cell is in last row, commits changes only and
If the active current cell is in edit mode, the changes will be committed and move the current cell below the active current cell. If the active current cell is in the last row, commits changes only remain in the same cell.

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +The [CurrentCell] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.SfDataGrid.html#Syncfusion_Maui_DataGrid_SfDataGrid_CurrentCell) can be moved to a particular [RowColumnIndex] (https:/
The [CurrentCell] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.SfDataGrid.html#Syncfusion_Maui_DataGrid_SfDataGrid_CurrentCell) can be moved to a particular [RowColumnIndex] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.GridCommon.ScrollAxis.RowColumnIndex.html) by using the [SfDataGrid.MoveCurrentCellTo()] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.SfDataGrid.html#Syncfusion_Maui_DataGrid_SfDataGrid_MoveCurrentCellTo_Syncfusion_Maui_GridCommon_ScrollAxis_RowColumnIndex_System_Boolean_) method. This method is not applicable when the `SfDataGrid.SelectionMode` is None or the `NavigationMode` is Row.

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +`DataGrid` allows you to clear the selection applied in the grid rows and columns either by setting the `SfDataGrid.SelectionMode` to None or by calling the [SfDataGrid.ClearSelection()] (https://hel
The `DataGrid` allows you to clear the selection applied in the grid rows and columns either by setting the `SfDataGrid.SelectionMode` to None or by calling the [SfDataGrid.ClearSelection()] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.SfDataGrid.html#Syncfusion_Maui_DataGrid_SfDataGrid_ClearSelection) method.

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +        //Clear selection using selection mode
//Clear selection using the selection mode.

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +        //Clear selection using clear selection method.
//Clear selection using the clear selection method.

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +[SelectionChanging] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.SfDataGrid.html#Syncfusion_Maui_DataGrid_SfDataGrid_SelectionChanging): This event is raised while selecting a row at
- [SelectionChanging] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.SfDataGrid.html#Syncfusion_Maui_DataGrid_SfDataGrid_SelectionChanging): This event is raised while selecting a row at the execution time before the row is selected. So it allows canceling the selection action by setting the [Cancel] (https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.canceleventargs.cancel?view=net-6.0#system-componentmodel-canceleventargs-cancel) property of [DataGridSelectionChangingEventArgs] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridSelectionChangingEventArgs.html).

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +[SelectionChanged] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.SfDataGrid.html#Syncfusion_Maui_DataGrid_SfDataGrid_SortColumnsChanged): This event is raised after a row is selected.
- [SelectionChanged] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.SfDataGrid.html#Syncfusion_Maui_DataGrid_SfDataGrid_SortColumnsChanged): This event is raised after a row is selected.

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +These two events are triggered with `DataGridSelectionChangingEventArgs` and [DataGridSelectionChangedEventArgs] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridSelectionChanged
These two events are triggered with the `DataGridSelectionChangingEventArgs` and [DataGridSelectionChangedEventArgs] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridSelectionChangedEventArgs.html) that contain the following properties:

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +[AddedRows] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridSelectionChangingEventArgs.html#Syncfusion_Maui_DataGrid_DataGridSelectionChangingEventArgs_AddedRows): Gets collecti
- [AddedRows] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridSelectionChangingEventArgs.html#Syncfusion_Maui_DataGrid_DataGridSelectionChangingEventArgs_AddedRows): Gets a collection of the underlying data objects added for the selection.

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +[RemovedRows] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridSelectionChangingEventArgs.html#Syncfusion_Maui_DataGrid_DataGridSelectionChangingEventArgs_RemovedRows): Gets coll
- [RemovedRows] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridSelectionChangingEventArgs.html#Syncfusion_Maui_DataGrid_DataGridSelectionChangingEventArgs_RemovedRows): Gets a collection of the underlying data objects removed from the selection.

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +To hook the SelectionChanging event and cancel the selection in following code example:
To hook the SelectionChanging event and cancel the selection, follow this code example:

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +To get the selected item in code-behind using the `SelectionChanged` event, follow the code example:
To get the selected item in a code-behind using the `SelectionChanged` event, follow this code example:

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +The datagrid provides the following Events to handle interactions to the cells,
The Datagrid provides the following Events to handle interactions to the cells.

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +* [CellDoubleTapped](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.SfDataGrid.html#Syncfusion_Maui_DataGrid_SfDataGrid_CellDoubleTapped) : Called when user is tapped a cell with a prim
* [CellDoubleTapped](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.SfDataGrid.html#Syncfusion_Maui_DataGrid_SfDataGrid_CellDoubleTapped): Called when the user has tapped a cell with a primary button at the same cell twice in quick succession.

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +* [CellTapped](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.SfDataGrid.html#Syncfusion_Maui_DataGrid_SfDataGrid_CellTapped) : Called when a tap with a cell has occurred.
* [CellTapped](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.SfDataGrid.html#Syncfusion_Maui_DataGrid_SfDataGrid_CellTapped): Called when a tap with a cell has occurred.

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +* [CellLongPress](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.SfDataGrid.html#Syncfusion_Maui_DataGrid_SfDataGrid_CellLongPress) : Called when a long press gesture with a primary but
* [CellLongPress](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.SfDataGrid.html#Syncfusion_Maui_DataGrid_SfDataGrid_CellLongPress): Called when a long-press gesture with a primary button has been recognized for a cell.

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +This event will be triggered while tapping a cell in DataGrid. This event has [DataGridCellTappedEventArgs](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridCellTappedEventArgs.ht
This event will be triggered while tapping a cell in the DataGrid. This event has the [DataGridCellTappedEventArgs](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridCellTappedEventArgs.html) as argument.

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +This event will be triggered while double tapping a cell in DataGrid. This event has [DataGridCellDoubleTappedEventArgs](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridCellDoubl
This event will be triggered while double-tapping a cell in the DataGrid. This event has the [DataGridCellDoubleTappedEventArgs](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridCellDoubleTappedEventArgs.html) as argument.

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +This event will be triggered while long pressing a cell in DataGrid. This event has [DataGridCellLongPressEventArgs](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridCellLongPress
This event will be triggered while long-pressing a cell in the DataGrid. This event has the [DataGridCellLongPressEventArgs](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridCellLongPressEventArgs.html) as argument.

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +The [SfDataGrid.CurrentRow] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.SfDataGrid.html#Syncfusion_Maui_DataGrid_SfDataGrid_CurrentRow) property holds the underlying data of the las
The [SfDataGrid.CurrentRow] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.SfDataGrid.html#Syncfusion_Maui_DataGrid_SfDataGrid_CurrentRow) property holds the underlying data of the last selected row in the data grid.

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +You can change the selection back color and text color by using [SelectionBackground] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridStyle.html#Syncfusion_Maui_DataGrid_DataGri
Change the selection back color and text color by using the [SelectionBackground] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridStyle.html#Syncfusion_Maui_DataGrid_DataGridStyle_SelectionBackground) and [SelectedRowTextColor] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridStyle.html#Syncfusion_Maui_DataGrid_DataGridStyle_SelectedRowTextColor) in the `SfDataGrid.DefaultStyle.`

2022-07-08 08:29 UTC, Chrispineagunja commented on MAUI/DataGrid/selection.md
> +You can change the current cell border color and width by using [CurrentCellBorderColor] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridStyle.html#Syncfusion_Maui_DataGrid_Data
Change the current cell border color and width by using the [CurrentCellBorderColor] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridStyle.html#Syncfusion_Maui_DataGrid_DataGridStyle_CurrentCellBorderColor) and [CurrentCellBorderWidth] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridStyle.html#Syncfusion_Maui_DataGrid_DataGridStyle_CurrentCellBorderWidth) in the SfDataGrid.DefaultStyle.

2022-07-08 12:07 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-2438_SelectionDataGrid](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1720/console)**

2022-07-08 12:08 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-2438_SelectionDataGrid](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1720/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1720/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1720/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1720/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1720/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1720/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1720/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-07-08 12:12 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-2438_SelectionDataGrid](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1721/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1721/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1721/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1721/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1721/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1721/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1721/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-07-08 13:33 UTC, merged