MAUI-2436 Write the UG documentation for conditional styling feature
syncfusion-content/maui-docs pull request #463
Opened 2022-07-12 10:51 UTC by FarjanaParveen

MAUI-2436 Write the UG documentation for conditional styling feature

2022-07-12 10:53 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1742/artifact/cireports/)<br/>Build Location: [MAUI-2436_Conditional-styling](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1742/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1742/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [4](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1742/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1742/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1742/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1742/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1742/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-07-12 11:01 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-2436_Conditional-styling](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1743/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1743/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1743/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1743/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1743/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1743/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1743/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-07-12 13:17 UTC, NeelakandanKannan requested changes
Get back to me with the changes.

2022-07-12 13:17 UTC, NeelakandanKannan commented on MAUI/DataGrid/conditional-styling.md
> +## Conditional Row Style
@FarjanaParveen  - Conditional row style

2022-07-12 13:17 UTC, NeelakandanKannan commented on MAUI/DataGrid/conditional-styling.md
> +The record rows ([DataGridRow] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridRow.html)) can be customized conditionally by changing its property value based on ‘cell value’ or
@FarjanaParveen  - 

The data rows can be customized conditionally by writing the style with converter for [DataGridRow] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridRow.html) control. Its `BindingContext` is underlying datasource object.

2022-07-12 13:17 UTC, NeelakandanKannan commented on MAUI/DataGrid/conditional-styling.md
> +## How to style a particular row based on RowIndex
How to style a particular row based on row index

2022-07-12 13:17 UTC, NeelakandanKannan commented on MAUI/DataGrid/conditional-styling.md
> +## Conditional Style for Column
@FarjanaParveen  - Conditional style for particular column

2022-07-12 13:17 UTC, NeelakandanKannan commented on MAUI/DataGrid/conditional-styling.md
> +The `SfDataGrid` provides the support for apply the conditional style for a column by using [CellStyle] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridColumn.html#Syncfusion_Ma
@FarjanaParveen  - 
The `SfDataGrid` provides the support to apply the conditional style for specific column by using [CellStyle] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridColumn.html#Syncfusion_Maui_DataGrid_DataGridColumn_CellStyleProperty) property in [DataGridColumn] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridColumn.html).

2022-07-13 05:21 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-2436_Conditional-styling](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1744/console)**

2022-07-13 05:24 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-2436_Conditional-styling](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1744/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1744/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1744/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1744/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1744/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1744/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1744/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-07-13 05:24 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-2436_Conditional-styling](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1745/console)**

2022-07-13 05:26 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-2436_Conditional-styling](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1745/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1745/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1745/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1745/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1745/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1745/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1745/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-07-13 06:21 UTC, NeelakandanKannan approved these changes
The changes are fine.

2022-07-14 06:20 UTC, Chrispineagunja commented on MAUI/DataGrid/conditional-styling.md
> +The [SfDataGrid] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.html) allows to customize the style of the individual cells and rows based on the requirements.
The [SfDataGrid] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.html) allows you to customize the style of the individual cells and rows based on the requirements.

2022-07-14 06:20 UTC, Chrispineagunja commented on MAUI/DataGrid/conditional-styling.md
> +The data rows can be customized conditionally by writing the style with converter for [DataGridRow] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridRow.html) control. Its Bindin
The data rows can be customized conditionally by writing the style with a converter for the [DataGridRow] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridRow.html) control. Its BindingContext is the underlying datasource object.

2022-07-14 06:20 UTC, Chrispineagunja commented on MAUI/DataGrid/conditional-styling.md
> +Styling can be applied to a particular row based on RowIndex property by writing the style for [DataGridRow] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridRow.html) TargetType
Styling can be applied to a particular row based on the RowIndex property by writing the style for the [DataGridRow] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridRow.html) TargetType.

2022-07-14 06:20 UTC, Chrispineagunja commented on MAUI/DataGrid/conditional-styling.md
> +Styling can be applied to a particular row based on RowData property by writing the style for [DataGridRow] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridRow.html) TargetType.
Styling can be applied to a particular row based on the RowData property by writing the style for the [DataGridRow] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridRow.html) TargetType.

2022-07-14 06:20 UTC, Chrispineagunja commented on MAUI/DataGrid/conditional-styling.md
> +The `SfDataGrid` provides the support to apply the conditional style for specific column by using [CellStyle] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridColumn.html#Syncfus
The `SfDataGrid` provides the support to apply the conditional style for specific column by using the [CellStyle] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridColumn.html#Syncfusion_Maui_DataGrid_DataGridColumn_CellStyleProperty) property in the [DataGridColumn] (https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.DataGridColumn.html).

2022-07-14 06:57 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-2436_Conditional-styling](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1767/console)**

2022-07-14 06:58 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-2436_Conditional-styling](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1767/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1767/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1767/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1767/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1767/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1767/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1767/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-07-14 07:00 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-2436_Conditional-styling](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1768/console)**

2022-07-14 07:01 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-2436_Conditional-styling](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1768/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1768/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1768/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1768/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1768/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1768/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1768/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-07-14 07:04 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-2436_Conditional-styling](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1770/console)**

2022-07-14 07:05 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-2436_Conditional-styling](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1770/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1770/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1770/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1770/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1770/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1770/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1770/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-07-14 07:30 UTC, NeelakandanKannan approved these changes
The changes are fine.

2022-07-14 07:30 UTC, merged