MAUI-1935- Updated the SfSlider code snippets and images
syncfusion-content/maui-docs pull request #549
Opened 2022-09-23 08:49 UTC by PraveenGopalsamy

Hi Team,

I have updated the wrong snippets and also added the images with default color changes.

Regards,
Praveen G.

2022-09-23 08:50 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-1935-SfSlider-UG-Changes](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1959/console)**

2022-09-23 08:51 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-1935-SfSlider-UG-Changes](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1959/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1959/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1959/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1959/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1959/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1959/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1959/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-09-23 09:00 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-1935-SfSlider-UG-Changes](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1960/console)**

2022-09-23 09:00 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-1935-SfSlider-UG-Changes](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1960/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1960/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1960/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1960/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1960/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1960/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1960/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-09-23 09:17 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-1935-SfSlider-UG-Changes](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1961/console)**

2022-09-23 09:18 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-1935-SfSlider-UG-Changes](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1961/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1961/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1961/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1961/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1961/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1961/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1961/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-09-26 02:52 UTC, PraveenGopalsamy commented
rebuild

2022-09-26 02:52 UTC, SyncfusionBuild commented
The CI [Job](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1970/console) is already running for this Pull Request/Merge Approved with latest commit id. You cannot trigger the duplicate job for same.

2022-09-26 02:52 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-1935-SfSlider-UG-Changes](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1970/console)**

2022-09-26 02:54 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-1935-SfSlider-UG-Changes](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1970/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1970/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1970/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1970/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1970/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1970/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1970/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-09-27 06:51 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-1935-SfSlider-UG-Changes](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1996/console)**

2022-09-27 06:53 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-1935-SfSlider-UG-Changes](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1996/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1996/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1996/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1996/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1996/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1996/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/1996/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-09-27 09:14 UTC, VijayakumarMariappan requested changes

2022-09-27 09:28 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-1935-SfSlider-UG-Changes](http://jenkins.syncfusion.com/job/Content/job/maui-docs/2005/console)**

2022-09-27 09:30 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-1935-SfSlider-UG-Changes](http://jenkins.syncfusion.com/job/Content/job/maui-docs/2005/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/2005/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/2005/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/2005/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/2005/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/2005/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/maui-docs/2005/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-09-27 09:30 UTC, PraveenGopalsamy commented on MAUI/DateTime-Slider/events-and-commands.md
> +        DragCompletedCommand = new Command<object>(OnDragCompleted);
No its not necessary. Removed.

2022-09-27 09:55 UTC, VijayakumarMariappan approved these changes
Changes are fine, @PraveenGopalsamy ensure the alignment and images in staging and acknowledge me

2022-09-27 09:55 UTC, merged