MAUI-3102 Updated the requirements document for MAUI
syncfusion-content/maui-docs pull request #632
Opened 2022-11-03 11:39 UTC by PaulAndersonS

Updated the requirements document for MAUI

2022-11-03 11:40 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [requirements](https://jenkins-ci.syncfusion.com/job/Content/job/maui-docs/1834/console)**

2022-11-03 11:49 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [requirements](https://jenkins-ci.syncfusion.com/job/Content/job/maui-docs/1834/console)**

2022-11-03 11:53 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [requirements](https://jenkins-ci.syncfusion.com/job/Content/job/maui-docs/1834/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/maui-docs/1834/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/maui-docs/1834/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/maui-docs/1834/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/maui-docs/1834/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/maui-docs/1834/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/maui-docs/1834/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-11-07 04:49 UTC, kselvaganapathy requested changes
Can we change the content like this?

Microsoft Visual Studio 2022 17.4.0 Preview 6.0 (.NET MAUI version 6.0.541) with .NET 6.0 and .NET 7.0, Microsoft Visual Studio 2022 17.4.0 (version no) with .NET 6.0 or Visual Studio 2022 for Mac 17.4 Preview.

2022-11-07 04:55 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [requirements](https://jenkins-ci.syncfusion.com/job/Content/job/maui-docs/1835/console)**

2022-11-07 04:56 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [requirements](https://jenkins-ci.syncfusion.com/job/Content/job/maui-docs/1835/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/maui-docs/1835/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/maui-docs/1835/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/maui-docs/1835/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/maui-docs/1835/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/maui-docs/1835/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/maui-docs/1835/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-11-07 05:08 UTC, Choza-rajan approved these changes

2022-11-07 05:09 UTC, merged

2022-11-15 04:25 UTC, kselvaganapathy reviewed
ok