MAUI-3668 UG for Pyramid Chart
syncfusion-content/maui-docs pull request #682
Opened 2022-12-06 09:57 UTC by SaiyathAliFathima

### Feature description ###
Preparing UG document for pyramid and funnel charts.

### Analysis and design ###
Referred the Circulart chart UG - https://help.syncfusion.com/maui/circular-charts/getting-started?cs-save-lang=1&cs-lang=csharp , pyramid and funnel UG in WinUI and flutter platforms - https://help.syncfusion.com/winui/pyramid-chart/getting-started ,https://help.syncfusion.com/flutter/pyramid-chart/chart-appearance

### Solution description ###
This UG document helps to guide the user to understand the feature.

### Areas affected and ensured ###
None

### API Changes ###
None

### Behavioral Changes ###
None

### Test cases ###
Not Applicable

### Testbed sample location ###
Not Applicable

### Does it have any known issues?
None

### Does it have memory leak?
None

2022-12-06 09:58 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-3668_Pyramid_Chart_UG](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1909/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1909/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1909/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1909/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1909/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1909/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1909/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-06 10:30 UTC, Saravanan-Madhesh requested changes

2022-12-06 10:30 UTC, Saravanan-Madhesh commented on MAUI/Pyramid-Charts/Getting-Started.md
> +            new Learning(){Name = "Before Sleeping", Value = 60},
Change some other use case, we modified it as not the proper use case

2022-12-06 10:30 UTC, Saravanan-Madhesh commented on MAUI/Pyramid-Charts/Overview.md
> +* Legends provide more information about the segments. If an item exceeds the available bounds, the legends can be wrapped or scrolled.
no wrap support, it only scrolled.

2022-12-06 10:38 UTC, SaiyathAliFathima commented on MAUI/Pyramid-Charts/Getting-Started.md
> + Binding `Data` to the Pyramid chart [ItemsSource]() property from its BindingContext to create our own pyramid chart.
I have updated this change

2022-12-06 12:31 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-3668_Pyramid_Chart_UG](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1910/console)**

2022-12-06 12:32 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-3668_Pyramid_Chart_UG](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1910/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1910/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1910/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1910/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1910/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1910/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1910/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-06 13:49 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-3668_Pyramid_Chart_UG](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1911/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1911/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1911/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1911/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1911/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1911/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1911/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-06 14:17 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-3668_Pyramid_Chart_UG](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1912/console)**

2022-12-06 14:18 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-3668_Pyramid_Chart_UG](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1912/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1912/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1912/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1912/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1912/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1912/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1912/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-07 06:47 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [MAUI-3668_Pyramid_Chart_UG](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1914/console)**

2022-12-07 06:48 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-3668_Pyramid_Chart_UG](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1914/console)**

2022-12-07 06:53 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-3668_Pyramid_Chart_UG](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1914/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1914/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1914/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1914/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1914/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1914/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1914/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-08 16:40 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [MAUI-3668_Pyramid_Chart_UG](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1937/console)**

2022-12-08 16:43 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [MAUI-3668_Pyramid_Chart_UG](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1937/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1937/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1937/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1937/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1937/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1937/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/1937/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-08 17:03 UTC, Saravanan-Madhesh approved these changes
The change are fine, please check in staging and update.

2022-12-08 17:03 UTC, merged