MAUI-4945 Updated the UG documentation content for Customization APIs and Text property and Completed event of SfAutoComplete and SfComboBox.
syncfusion-content/maui-docs pull request #973
Opened 2023-03-09 11:14 UTC by BrundhaVelusamy

Prepared UG for .NET MAUI SfAutoComplete and SfComboBox controls for ItemTemplate customization support,  Text property, and Completed event.

2023-03-09 11:15 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Ug_Documentation](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2815/console)**

2023-03-09 11:17 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Ug_Documentation](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2815/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2815/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2815/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2815/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2815/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2815/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2815/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-03-09 11:32 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Ug_Documentation](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2816/console)**

2023-03-09 11:33 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Ug_Documentation](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2816/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2816/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2816/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2816/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2816/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2816/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2816/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-03-13 06:59 UTC, florenceliliana requested changes

2023-03-13 06:59 UTC, florenceliliana commented on MAUI/Autocomplete/Getting-Started.md
> +The [Text]() property used to gets the user-submitted text in the [SfAutoComplete](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.Inputs.SfAutocomplete.html). The default value of the `Text` pro
The [Text]() property is used to get the user-submitted text in the [SfAutoComplete](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.Inputs.SfAutocomplete.html). The default value of the `Text` property is the `string.Empty`.

2023-03-13 06:59 UTC, florenceliliana commented on MAUI/ComboBox/Getting-Started.md
> +The [Text]() property used to gets the user-submitted text in the [SfComboBox](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.Inputs.SfComboBox.html) editable mode. The default value of the `Tex
The [Text]() property used to get the user-submitted text in the [SfComboBox](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.Inputs.SfComboBox.html) editable mode. The default value of the `Text` property is the `string.Empty`.

2023-03-13 06:59 UTC, florenceliliana commented on MAUI/ComboBox/UI-Customization.md
> +The [ItemTemplate]() property helps you to decorate drop-down items conditionally based on their content using the custom templates. The default value of `ItemTemplate` is `null`.
The [ItemTemplate]() property helps you to decorate drop-down items conditionally based on their content using the custom templates. The default value of the `ItemTemplate` is `null.`

2023-03-13 06:59 UTC, florenceliliana commented on MAUI/ComboBox/UI-Customization.md
> +The [Completed]() event is raised when the user finalizes the text in the [SfComboBox](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.Inputs.SfComboBox.html) editable mode by pressing return key
The [Completed]() event is raised when the user finalizes the text in the [SfComboBox](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.Inputs.SfComboBox.html) editable mode by pressing return key on the keyboard. The handler for the event is a generic event handler, taking the `sender` and `EventArgs`(the `EventArgs` value is `string.Empty`):

2023-03-13 07:20 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [Ug_Documentation](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2853/console)**

2023-03-13 07:23 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [Ug_Documentation](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2854/console)**

2023-03-13 07:24 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Ug_Documentation](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2853/console)**

2023-03-13 07:24 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Ug_Documentation](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2854/console)**

2023-03-13 07:27 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Ug_Documentation](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2854/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2854/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2854/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2854/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2854/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2854/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2854/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-03-13 07:27 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Ug_Documentation](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2853/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2853/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2853/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2853/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2853/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2853/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2853/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-03-13 11:45 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Ug_Documentation](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2874/console)**

2023-03-13 11:47 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Ug_Documentation](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2874/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2874/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2874/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2874/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2874/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2874/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/maui-docs/2874/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-03-27 08:56 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Ug_Documentation](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3191/console)**

2023-03-27 08:56 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Ug_Documentation](https://jenkins.syncfusion.com/job/Content/job/maui-docs/3191/)<br/>**

2023-03-27 09:20 UTC, PaulAndersonS approved these changes

2023-03-27 09:21 UTC, merged